// Code generated by ent, DO NOT EDIT.

package setting

import (
	"cctv/shared/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Setting {
	return predicate.Setting(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Setting {
	return predicate.Setting(sql.FieldContainsFold(FieldID, id))
}

// NvrStatus applies equality check predicate on the "nvr_status" field. It's identical to NvrStatusEQ.
func NvrStatus(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldNvrStatus, v))
}

// StorageQuotaGB applies equality check predicate on the "storage_quota_gb" field. It's identical to StorageQuotaGBEQ.
func StorageQuotaGB(v int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldStorageQuotaGB, v))
}

// RetentionDays applies equality check predicate on the "retention_days" field. It's identical to RetentionDaysEQ.
func RetentionDays(v int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldRetentionDays, v))
}

// NvrStatusEQ applies the EQ predicate on the "nvr_status" field.
func NvrStatusEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldNvrStatus, v))
}

// NvrStatusNEQ applies the NEQ predicate on the "nvr_status" field.
func NvrStatusNEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldNvrStatus, v))
}

// StorageQuotaGBEQ applies the EQ predicate on the "storage_quota_gb" field.
func StorageQuotaGBEQ(v int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldStorageQuotaGB, v))
}

// StorageQuotaGBNEQ applies the NEQ predicate on the "storage_quota_gb" field.
func StorageQuotaGBNEQ(v int) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldStorageQuotaGB, v))
}

// StorageQuotaGBIn applies the In predicate on the "storage_quota_gb" field.
func StorageQuotaGBIn(vs ...int) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldStorageQuotaGB, vs...))
}

// StorageQuotaGBNotIn applies the NotIn predicate on the "storage_quota_gb" field.
func StorageQuotaGBNotIn(vs ...int) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldStorageQuotaGB, vs...))
}

// StorageQuotaGBGT applies the GT predicate on the "storage_quota_gb" field.
func StorageQuotaGBGT(v int) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldStorageQuotaGB, v))
}

// StorageQuotaGBGTE applies the GTE predicate on the "storage_quota_gb" field.
func StorageQuotaGBGTE(v int) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldStorageQuotaGB, v))
}

// StorageQuotaGBLT applies the LT predicate on the "storage_quota_gb" field.
func StorageQuotaGBLT(v int) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldStorageQuotaGB, v))
}

// StorageQuotaGBLTE applies the LTE predicate on the "storage_quota_gb" field.
func StorageQuotaGBLTE(v int) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldStorageQuotaGB, v))
}

// RetentionDaysEQ applies the EQ predicate on the "retention_days" field.
func RetentionDaysEQ(v int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldRetentionDays, v))
}

// RetentionDaysNEQ applies the NEQ predicate on the "retention_days" field.
func RetentionDaysNEQ(v int) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldRetentionDays, v))
}

// RetentionDaysIn applies the In predicate on the "retention_days" field.
func RetentionDaysIn(vs ...int) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldRetentionDays, vs...))
}

// RetentionDaysNotIn applies the NotIn predicate on the "retention_days" field.
func RetentionDaysNotIn(vs ...int) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldRetentionDays, vs...))
}

// RetentionDaysGT applies the GT predicate on the "retention_days" field.
func RetentionDaysGT(v int) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldRetentionDays, v))
}

// RetentionDaysGTE applies the GTE predicate on the "retention_days" field.
func RetentionDaysGTE(v int) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldRetentionDays, v))
}

// RetentionDaysLT applies the LT predicate on the "retention_days" field.
func RetentionDaysLT(v int) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldRetentionDays, v))
}

// RetentionDaysLTE applies the LTE predicate on the "retention_days" field.
func RetentionDaysLTE(v int) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldRetentionDays, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.NotPredicates(p))
}
