// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/ent/camera"
	"cctv/ent/recording"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecordingCreate is the builder for creating a Recording entity.
type RecordingCreate struct {
	config
	mutation *RecordingMutation
	hooks    []Hook
}

// SetCameraID sets the "camera_id" field.
func (_c *RecordingCreate) SetCameraID(v string) *RecordingCreate {
	_c.mutation.SetCameraID(v)
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *RecordingCreate) SetStartAt(v time.Time) *RecordingCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetEndAt sets the "end_at" field.
func (_c *RecordingCreate) SetEndAt(v time.Time) *RecordingCreate {
	_c.mutation.SetEndAt(v)
	return _c
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_c *RecordingCreate) SetDurationSeconds(v int) *RecordingCreate {
	_c.mutation.SetDurationSeconds(v)
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *RecordingCreate) SetFilePath(v string) *RecordingCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *RecordingCreate) SetSizeBytes(v int64) *RecordingCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecordingCreate) SetCreatedAt(v time.Time) *RecordingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecordingCreate) SetNillableCreatedAt(v *time.Time) *RecordingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RecordingCreate) SetID(v string) *RecordingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RecordingCreate) SetNillableID(v *string) *RecordingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCamera sets the "camera" edge to the Camera entity.
func (_c *RecordingCreate) SetCamera(v *Camera) *RecordingCreate {
	return _c.SetCameraID(v.ID)
}

// Mutation returns the RecordingMutation object of the builder.
func (_c *RecordingCreate) Mutation() *RecordingMutation {
	return _c.mutation
}

// Save creates the Recording in the database.
func (_c *RecordingCreate) Save(ctx context.Context) (*Recording, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecordingCreate) SaveX(ctx context.Context) *Recording {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecordingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := recording.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := recording.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecordingCreate) check() error {
	if _, ok := _c.mutation.CameraID(); !ok {
		return &ValidationError{Name: "camera_id", err: errors.New(`ent: missing required field "Recording.camera_id"`)}
	}
	if _, ok := _c.mutation.StartAt(); !ok {
		return &ValidationError{Name: "start_at", err: errors.New(`ent: missing required field "Recording.start_at"`)}
	}
	if _, ok := _c.mutation.EndAt(); !ok {
		return &ValidationError{Name: "end_at", err: errors.New(`ent: missing required field "Recording.end_at"`)}
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		return &ValidationError{Name: "duration_seconds", err: errors.New(`ent: missing required field "Recording.duration_seconds"`)}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "Recording.file_path"`)}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "Recording.size_bytes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Recording.created_at"`)}
	}
	if len(_c.mutation.CameraIDs()) == 0 {
		return &ValidationError{Name: "camera", err: errors.New(`ent: missing required edge "Recording.camera"`)}
	}
	return nil
}

func (_c *RecordingCreate) sqlSave(ctx context.Context) (*Recording, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Recording.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecordingCreate) createSpec() (*Recording, *sqlgraph.CreateSpec) {
	var (
		_node = &Recording{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recording.Table, sqlgraph.NewFieldSpec(recording.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(recording.FieldStartAt, field.TypeTime, value)
		_node.StartAt = value
	}
	if value, ok := _c.mutation.EndAt(); ok {
		_spec.SetField(recording.FieldEndAt, field.TypeTime, value)
		_node.EndAt = value
	}
	if value, ok := _c.mutation.DurationSeconds(); ok {
		_spec.SetField(recording.FieldDurationSeconds, field.TypeInt, value)
		_node.DurationSeconds = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(recording.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(recording.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recording.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CameraIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recording.CameraTable,
			Columns: []string{recording.CameraColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(camera.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CameraID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecordingCreateBulk is the builder for creating many Recording entities in bulk.
type RecordingCreateBulk struct {
	config
	err      error
	builders []*RecordingCreate
}

// Save creates the Recording entities in the database.
func (_c *RecordingCreateBulk) Save(ctx context.Context) ([]*Recording, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Recording, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecordingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecordingCreateBulk) SaveX(ctx context.Context) []*Recording {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
