// Code generated by ent, DO NOT EDIT.

package memberface

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the memberface type in the database.
	Label = "member_face"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMemberID holds the string denoting the member_id field in the database.
	FieldMemberID = "member_id"
	// FieldEmbedding holds the string denoting the embedding field in the database.
	FieldEmbedding = "embedding"
	// FieldSampleImageURL holds the string denoting the sample_image_url field in the database.
	FieldSampleImageURL = "sample_image_url"
	// FieldQualityScore holds the string denoting the quality_score field in the database.
	FieldQualityScore = "quality_score"
	// FieldYaw holds the string denoting the yaw field in the database.
	FieldYaw = "yaw"
	// FieldPitch holds the string denoting the pitch field in the database.
	FieldPitch = "pitch"
	// FieldBlurScore holds the string denoting the blur_score field in the database.
	FieldBlurScore = "blur_score"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMember holds the string denoting the member edge name in mutations.
	EdgeMember = "member"
	// Table holds the table name of the memberface in the database.
	Table = "member_faces"
	// MemberTable is the table that holds the member relation/edge.
	MemberTable = "member_faces"
	// MemberInverseTable is the table name for the Member entity.
	// It exists in this package in order to avoid circular dependency with the "member" package.
	MemberInverseTable = "members"
	// MemberColumn is the table column denoting the member relation/edge.
	MemberColumn = "member_id"
)

// Columns holds all SQL columns for memberface fields.
var Columns = []string{
	FieldID,
	FieldMemberID,
	FieldEmbedding,
	FieldSampleImageURL,
	FieldQualityScore,
	FieldYaw,
	FieldPitch,
	FieldBlurScore,
	FieldIsActive,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSampleImageURL holds the default value on creation for the "sample_image_url" field.
	DefaultSampleImageURL string
	// DefaultQualityScore holds the default value on creation for the "quality_score" field.
	DefaultQualityScore float64
	// DefaultYaw holds the default value on creation for the "yaw" field.
	DefaultYaw float64
	// DefaultPitch holds the default value on creation for the "pitch" field.
	DefaultPitch float64
	// DefaultBlurScore holds the default value on creation for the "blur_score" field.
	DefaultBlurScore float64
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the MemberFace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMemberID orders the results by the member_id field.
func ByMemberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberID, opts...).ToFunc()
}

// BySampleImageURL orders the results by the sample_image_url field.
func BySampleImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSampleImageURL, opts...).ToFunc()
}

// ByQualityScore orders the results by the quality_score field.
func ByQualityScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualityScore, opts...).ToFunc()
}

// ByYaw orders the results by the yaw field.
func ByYaw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYaw, opts...).ToFunc()
}

// ByPitch orders the results by the pitch field.
func ByPitch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPitch, opts...).ToFunc()
}

// ByBlurScore orders the results by the blur_score field.
func ByBlurScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlurScore, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMemberField orders the results by member field.
func ByMemberField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemberStep(), sql.OrderByField(field, opts...))
	}
}
func newMemberStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemberInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
	)
}
