// Code generated by ent, DO NOT EDIT.

package memberface

import (
	"cctv/shared/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldContainsFold(FieldID, id))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldMemberID, v))
}

// SampleImageURL applies equality check predicate on the "sample_image_url" field. It's identical to SampleImageURLEQ.
func SampleImageURL(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldSampleImageURL, v))
}

// QualityScore applies equality check predicate on the "quality_score" field. It's identical to QualityScoreEQ.
func QualityScore(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldQualityScore, v))
}

// Yaw applies equality check predicate on the "yaw" field. It's identical to YawEQ.
func Yaw(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldYaw, v))
}

// Pitch applies equality check predicate on the "pitch" field. It's identical to PitchEQ.
func Pitch(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldPitch, v))
}

// BlurScore applies equality check predicate on the "blur_score" field. It's identical to BlurScoreEQ.
func BlurScore(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldBlurScore, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldCreatedAt, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNotIn(FieldMemberID, vs...))
}

// MemberIDGT applies the GT predicate on the "member_id" field.
func MemberIDGT(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGT(FieldMemberID, v))
}

// MemberIDGTE applies the GTE predicate on the "member_id" field.
func MemberIDGTE(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGTE(FieldMemberID, v))
}

// MemberIDLT applies the LT predicate on the "member_id" field.
func MemberIDLT(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLT(FieldMemberID, v))
}

// MemberIDLTE applies the LTE predicate on the "member_id" field.
func MemberIDLTE(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLTE(FieldMemberID, v))
}

// MemberIDContains applies the Contains predicate on the "member_id" field.
func MemberIDContains(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldContains(FieldMemberID, v))
}

// MemberIDHasPrefix applies the HasPrefix predicate on the "member_id" field.
func MemberIDHasPrefix(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldHasPrefix(FieldMemberID, v))
}

// MemberIDHasSuffix applies the HasSuffix predicate on the "member_id" field.
func MemberIDHasSuffix(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldHasSuffix(FieldMemberID, v))
}

// MemberIDEqualFold applies the EqualFold predicate on the "member_id" field.
func MemberIDEqualFold(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEqualFold(FieldMemberID, v))
}

// MemberIDContainsFold applies the ContainsFold predicate on the "member_id" field.
func MemberIDContainsFold(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldContainsFold(FieldMemberID, v))
}

// SampleImageURLEQ applies the EQ predicate on the "sample_image_url" field.
func SampleImageURLEQ(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldSampleImageURL, v))
}

// SampleImageURLNEQ applies the NEQ predicate on the "sample_image_url" field.
func SampleImageURLNEQ(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldSampleImageURL, v))
}

// SampleImageURLIn applies the In predicate on the "sample_image_url" field.
func SampleImageURLIn(vs ...string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldIn(FieldSampleImageURL, vs...))
}

// SampleImageURLNotIn applies the NotIn predicate on the "sample_image_url" field.
func SampleImageURLNotIn(vs ...string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNotIn(FieldSampleImageURL, vs...))
}

// SampleImageURLGT applies the GT predicate on the "sample_image_url" field.
func SampleImageURLGT(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGT(FieldSampleImageURL, v))
}

// SampleImageURLGTE applies the GTE predicate on the "sample_image_url" field.
func SampleImageURLGTE(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGTE(FieldSampleImageURL, v))
}

// SampleImageURLLT applies the LT predicate on the "sample_image_url" field.
func SampleImageURLLT(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLT(FieldSampleImageURL, v))
}

// SampleImageURLLTE applies the LTE predicate on the "sample_image_url" field.
func SampleImageURLLTE(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLTE(FieldSampleImageURL, v))
}

// SampleImageURLContains applies the Contains predicate on the "sample_image_url" field.
func SampleImageURLContains(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldContains(FieldSampleImageURL, v))
}

// SampleImageURLHasPrefix applies the HasPrefix predicate on the "sample_image_url" field.
func SampleImageURLHasPrefix(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldHasPrefix(FieldSampleImageURL, v))
}

// SampleImageURLHasSuffix applies the HasSuffix predicate on the "sample_image_url" field.
func SampleImageURLHasSuffix(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldHasSuffix(FieldSampleImageURL, v))
}

// SampleImageURLEqualFold applies the EqualFold predicate on the "sample_image_url" field.
func SampleImageURLEqualFold(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEqualFold(FieldSampleImageURL, v))
}

// SampleImageURLContainsFold applies the ContainsFold predicate on the "sample_image_url" field.
func SampleImageURLContainsFold(v string) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldContainsFold(FieldSampleImageURL, v))
}

// QualityScoreEQ applies the EQ predicate on the "quality_score" field.
func QualityScoreEQ(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldQualityScore, v))
}

// QualityScoreNEQ applies the NEQ predicate on the "quality_score" field.
func QualityScoreNEQ(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldQualityScore, v))
}

// QualityScoreIn applies the In predicate on the "quality_score" field.
func QualityScoreIn(vs ...float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldIn(FieldQualityScore, vs...))
}

// QualityScoreNotIn applies the NotIn predicate on the "quality_score" field.
func QualityScoreNotIn(vs ...float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNotIn(FieldQualityScore, vs...))
}

// QualityScoreGT applies the GT predicate on the "quality_score" field.
func QualityScoreGT(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGT(FieldQualityScore, v))
}

// QualityScoreGTE applies the GTE predicate on the "quality_score" field.
func QualityScoreGTE(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGTE(FieldQualityScore, v))
}

// QualityScoreLT applies the LT predicate on the "quality_score" field.
func QualityScoreLT(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLT(FieldQualityScore, v))
}

// QualityScoreLTE applies the LTE predicate on the "quality_score" field.
func QualityScoreLTE(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLTE(FieldQualityScore, v))
}

// YawEQ applies the EQ predicate on the "yaw" field.
func YawEQ(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldYaw, v))
}

// YawNEQ applies the NEQ predicate on the "yaw" field.
func YawNEQ(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldYaw, v))
}

// YawIn applies the In predicate on the "yaw" field.
func YawIn(vs ...float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldIn(FieldYaw, vs...))
}

// YawNotIn applies the NotIn predicate on the "yaw" field.
func YawNotIn(vs ...float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNotIn(FieldYaw, vs...))
}

// YawGT applies the GT predicate on the "yaw" field.
func YawGT(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGT(FieldYaw, v))
}

// YawGTE applies the GTE predicate on the "yaw" field.
func YawGTE(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGTE(FieldYaw, v))
}

// YawLT applies the LT predicate on the "yaw" field.
func YawLT(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLT(FieldYaw, v))
}

// YawLTE applies the LTE predicate on the "yaw" field.
func YawLTE(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLTE(FieldYaw, v))
}

// PitchEQ applies the EQ predicate on the "pitch" field.
func PitchEQ(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldPitch, v))
}

// PitchNEQ applies the NEQ predicate on the "pitch" field.
func PitchNEQ(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldPitch, v))
}

// PitchIn applies the In predicate on the "pitch" field.
func PitchIn(vs ...float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldIn(FieldPitch, vs...))
}

// PitchNotIn applies the NotIn predicate on the "pitch" field.
func PitchNotIn(vs ...float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNotIn(FieldPitch, vs...))
}

// PitchGT applies the GT predicate on the "pitch" field.
func PitchGT(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGT(FieldPitch, v))
}

// PitchGTE applies the GTE predicate on the "pitch" field.
func PitchGTE(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGTE(FieldPitch, v))
}

// PitchLT applies the LT predicate on the "pitch" field.
func PitchLT(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLT(FieldPitch, v))
}

// PitchLTE applies the LTE predicate on the "pitch" field.
func PitchLTE(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLTE(FieldPitch, v))
}

// BlurScoreEQ applies the EQ predicate on the "blur_score" field.
func BlurScoreEQ(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldBlurScore, v))
}

// BlurScoreNEQ applies the NEQ predicate on the "blur_score" field.
func BlurScoreNEQ(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldBlurScore, v))
}

// BlurScoreIn applies the In predicate on the "blur_score" field.
func BlurScoreIn(vs ...float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldIn(FieldBlurScore, vs...))
}

// BlurScoreNotIn applies the NotIn predicate on the "blur_score" field.
func BlurScoreNotIn(vs ...float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNotIn(FieldBlurScore, vs...))
}

// BlurScoreGT applies the GT predicate on the "blur_score" field.
func BlurScoreGT(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGT(FieldBlurScore, v))
}

// BlurScoreGTE applies the GTE predicate on the "blur_score" field.
func BlurScoreGTE(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGTE(FieldBlurScore, v))
}

// BlurScoreLT applies the LT predicate on the "blur_score" field.
func BlurScoreLT(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLT(FieldBlurScore, v))
}

// BlurScoreLTE applies the LTE predicate on the "blur_score" field.
func BlurScoreLTE(v float64) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLTE(FieldBlurScore, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MemberFace {
	return predicate.MemberFace(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.MemberFace {
	return predicate.MemberFace(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.Member) predicate.MemberFace {
	return predicate.MemberFace(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemberFace) predicate.MemberFace {
	return predicate.MemberFace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemberFace) predicate.MemberFace {
	return predicate.MemberFace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemberFace) predicate.MemberFace {
	return predicate.MemberFace(sql.NotPredicates(p))
}
