// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/ent/camera"
	"cctv/ent/predicate"
	"cctv/ent/recording"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CameraUpdate is the builder for updating Camera entities.
type CameraUpdate struct {
	config
	hooks    []Hook
	mutation *CameraMutation
}

// Where appends a list predicates to the CameraUpdate builder.
func (_u *CameraUpdate) Where(ps ...predicate.Camera) *CameraUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CameraUpdate) SetName(v string) *CameraUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CameraUpdate) SetNillableName(v *string) *CameraUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *CameraUpdate) SetHost(v string) *CameraUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *CameraUpdate) SetNillableHost(v *string) *CameraUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetRtspPort sets the "rtsp_port" field.
func (_u *CameraUpdate) SetRtspPort(v int) *CameraUpdate {
	_u.mutation.ResetRtspPort()
	_u.mutation.SetRtspPort(v)
	return _u
}

// SetNillableRtspPort sets the "rtsp_port" field if the given value is not nil.
func (_u *CameraUpdate) SetNillableRtspPort(v *int) *CameraUpdate {
	if v != nil {
		_u.SetRtspPort(*v)
	}
	return _u
}

// AddRtspPort adds value to the "rtsp_port" field.
func (_u *CameraUpdate) AddRtspPort(v int) *CameraUpdate {
	_u.mutation.AddRtspPort(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CameraUpdate) SetIsActive(v bool) *CameraUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CameraUpdate) SetNillableIsActive(v *bool) *CameraUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CameraUpdate) SetCreatedAt(v time.Time) *CameraUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CameraUpdate) SetNillableCreatedAt(v *time.Time) *CameraUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CameraUpdate) SetUpdatedAt(v time.Time) *CameraUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRecordingIDs adds the "recordings" edge to the Recording entity by IDs.
func (_u *CameraUpdate) AddRecordingIDs(ids ...int) *CameraUpdate {
	_u.mutation.AddRecordingIDs(ids...)
	return _u
}

// AddRecordings adds the "recordings" edges to the Recording entity.
func (_u *CameraUpdate) AddRecordings(v ...*Recording) *CameraUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordingIDs(ids...)
}

// Mutation returns the CameraMutation object of the builder.
func (_u *CameraUpdate) Mutation() *CameraMutation {
	return _u.mutation
}

// ClearRecordings clears all "recordings" edges to the Recording entity.
func (_u *CameraUpdate) ClearRecordings() *CameraUpdate {
	_u.mutation.ClearRecordings()
	return _u
}

// RemoveRecordingIDs removes the "recordings" edge to Recording entities by IDs.
func (_u *CameraUpdate) RemoveRecordingIDs(ids ...int) *CameraUpdate {
	_u.mutation.RemoveRecordingIDs(ids...)
	return _u
}

// RemoveRecordings removes "recordings" edges to Recording entities.
func (_u *CameraUpdate) RemoveRecordings(v ...*Recording) *CameraUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CameraUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CameraUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CameraUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CameraUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CameraUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := camera.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CameraUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := camera.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Camera.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := camera.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Camera.host": %w`, err)}
		}
	}
	return nil
}

func (_u *CameraUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(camera.Table, camera.Columns, sqlgraph.NewFieldSpec(camera.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(camera.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(camera.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.RtspPort(); ok {
		_spec.SetField(camera.FieldRtspPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRtspPort(); ok {
		_spec.AddField(camera.FieldRtspPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(camera.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(camera.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(camera.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RecordingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   camera.RecordingsTable,
			Columns: []string{camera.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordingsIDs(); len(nodes) > 0 && !_u.mutation.RecordingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   camera.RecordingsTable,
			Columns: []string{camera.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   camera.RecordingsTable,
			Columns: []string{camera.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{camera.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CameraUpdateOne is the builder for updating a single Camera entity.
type CameraUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CameraMutation
}

// SetName sets the "name" field.
func (_u *CameraUpdateOne) SetName(v string) *CameraUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CameraUpdateOne) SetNillableName(v *string) *CameraUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *CameraUpdateOne) SetHost(v string) *CameraUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *CameraUpdateOne) SetNillableHost(v *string) *CameraUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetRtspPort sets the "rtsp_port" field.
func (_u *CameraUpdateOne) SetRtspPort(v int) *CameraUpdateOne {
	_u.mutation.ResetRtspPort()
	_u.mutation.SetRtspPort(v)
	return _u
}

// SetNillableRtspPort sets the "rtsp_port" field if the given value is not nil.
func (_u *CameraUpdateOne) SetNillableRtspPort(v *int) *CameraUpdateOne {
	if v != nil {
		_u.SetRtspPort(*v)
	}
	return _u
}

// AddRtspPort adds value to the "rtsp_port" field.
func (_u *CameraUpdateOne) AddRtspPort(v int) *CameraUpdateOne {
	_u.mutation.AddRtspPort(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CameraUpdateOne) SetIsActive(v bool) *CameraUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CameraUpdateOne) SetNillableIsActive(v *bool) *CameraUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CameraUpdateOne) SetCreatedAt(v time.Time) *CameraUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CameraUpdateOne) SetNillableCreatedAt(v *time.Time) *CameraUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CameraUpdateOne) SetUpdatedAt(v time.Time) *CameraUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRecordingIDs adds the "recordings" edge to the Recording entity by IDs.
func (_u *CameraUpdateOne) AddRecordingIDs(ids ...int) *CameraUpdateOne {
	_u.mutation.AddRecordingIDs(ids...)
	return _u
}

// AddRecordings adds the "recordings" edges to the Recording entity.
func (_u *CameraUpdateOne) AddRecordings(v ...*Recording) *CameraUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordingIDs(ids...)
}

// Mutation returns the CameraMutation object of the builder.
func (_u *CameraUpdateOne) Mutation() *CameraMutation {
	return _u.mutation
}

// ClearRecordings clears all "recordings" edges to the Recording entity.
func (_u *CameraUpdateOne) ClearRecordings() *CameraUpdateOne {
	_u.mutation.ClearRecordings()
	return _u
}

// RemoveRecordingIDs removes the "recordings" edge to Recording entities by IDs.
func (_u *CameraUpdateOne) RemoveRecordingIDs(ids ...int) *CameraUpdateOne {
	_u.mutation.RemoveRecordingIDs(ids...)
	return _u
}

// RemoveRecordings removes "recordings" edges to Recording entities.
func (_u *CameraUpdateOne) RemoveRecordings(v ...*Recording) *CameraUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordingIDs(ids...)
}

// Where appends a list predicates to the CameraUpdate builder.
func (_u *CameraUpdateOne) Where(ps ...predicate.Camera) *CameraUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CameraUpdateOne) Select(field string, fields ...string) *CameraUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Camera entity.
func (_u *CameraUpdateOne) Save(ctx context.Context) (*Camera, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CameraUpdateOne) SaveX(ctx context.Context) *Camera {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CameraUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CameraUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CameraUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := camera.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CameraUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := camera.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Camera.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := camera.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Camera.host": %w`, err)}
		}
	}
	return nil
}

func (_u *CameraUpdateOne) sqlSave(ctx context.Context) (_node *Camera, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(camera.Table, camera.Columns, sqlgraph.NewFieldSpec(camera.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Camera.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, camera.FieldID)
		for _, f := range fields {
			if !camera.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != camera.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(camera.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(camera.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.RtspPort(); ok {
		_spec.SetField(camera.FieldRtspPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRtspPort(); ok {
		_spec.AddField(camera.FieldRtspPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(camera.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(camera.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(camera.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RecordingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   camera.RecordingsTable,
			Columns: []string{camera.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordingsIDs(); len(nodes) > 0 && !_u.mutation.RecordingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   camera.RecordingsTable,
			Columns: []string{camera.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   camera.RecordingsTable,
			Columns: []string{camera.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Camera{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{camera.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
