// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/ent/camera"
	"cctv/ent/recording"
	"cctv/ent/schema"
	"cctv/ent/session"
	"cctv/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cameraFields := schema.Camera{}.Fields()
	_ = cameraFields
	// cameraDescName is the schema descriptor for name field.
	cameraDescName := cameraFields[0].Descriptor()
	// camera.NameValidator is a validator for the "name" field. It is called by the builders before save.
	camera.NameValidator = cameraDescName.Validators[0].(func(string) error)
	// cameraDescHost is the schema descriptor for host field.
	cameraDescHost := cameraFields[1].Descriptor()
	// camera.HostValidator is a validator for the "host" field. It is called by the builders before save.
	camera.HostValidator = cameraDescHost.Validators[0].(func(string) error)
	// cameraDescBrand is the schema descriptor for brand field.
	cameraDescBrand := cameraFields[2].Descriptor()
	// camera.DefaultBrand holds the default value on creation for the brand field.
	camera.DefaultBrand = cameraDescBrand.Default.(string)
	// cameraDescRtspPort is the schema descriptor for rtsp_port field.
	cameraDescRtspPort := cameraFields[3].Descriptor()
	// camera.DefaultRtspPort holds the default value on creation for the rtsp_port field.
	camera.DefaultRtspPort = cameraDescRtspPort.Default.(int)
	// cameraDescRtspTransport is the schema descriptor for rtsp_transport field.
	cameraDescRtspTransport := cameraFields[4].Descriptor()
	// camera.DefaultRtspTransport holds the default value on creation for the rtsp_transport field.
	camera.DefaultRtspTransport = cameraDescRtspTransport.Default.(string)
	// cameraDescSegmentDuration is the schema descriptor for segment_duration field.
	cameraDescSegmentDuration := cameraFields[5].Descriptor()
	// camera.DefaultSegmentDuration holds the default value on creation for the segment_duration field.
	camera.DefaultSegmentDuration = cameraDescSegmentDuration.Default.(int)
	// cameraDescVideoCodec is the schema descriptor for video_codec field.
	cameraDescVideoCodec := cameraFields[6].Descriptor()
	// camera.DefaultVideoCodec holds the default value on creation for the video_codec field.
	camera.DefaultVideoCodec = cameraDescVideoCodec.Default.(string)
	// cameraDescAudioMode is the schema descriptor for audio_mode field.
	cameraDescAudioMode := cameraFields[7].Descriptor()
	// camera.DefaultAudioMode holds the default value on creation for the audio_mode field.
	camera.DefaultAudioMode = cameraDescAudioMode.Default.(string)
	// cameraDescExtraArgs is the schema descriptor for extra_args field.
	cameraDescExtraArgs := cameraFields[8].Descriptor()
	// camera.DefaultExtraArgs holds the default value on creation for the extra_args field.
	camera.DefaultExtraArgs = cameraDescExtraArgs.Default.(string)
	// cameraDescIsActive is the schema descriptor for is_active field.
	cameraDescIsActive := cameraFields[9].Descriptor()
	// camera.DefaultIsActive holds the default value on creation for the is_active field.
	camera.DefaultIsActive = cameraDescIsActive.Default.(bool)
	// cameraDescCreatedAt is the schema descriptor for created_at field.
	cameraDescCreatedAt := cameraFields[10].Descriptor()
	// camera.DefaultCreatedAt holds the default value on creation for the created_at field.
	camera.DefaultCreatedAt = cameraDescCreatedAt.Default.(func() time.Time)
	// cameraDescUpdatedAt is the schema descriptor for updated_at field.
	cameraDescUpdatedAt := cameraFields[11].Descriptor()
	// camera.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	camera.DefaultUpdatedAt = cameraDescUpdatedAt.Default.(func() time.Time)
	// camera.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	camera.UpdateDefaultUpdatedAt = cameraDescUpdatedAt.UpdateDefault.(func() time.Time)
	recordingFields := schema.Recording{}.Fields()
	_ = recordingFields
	// recordingDescCreatedAt is the schema descriptor for created_at field.
	recordingDescCreatedAt := recordingFields[5].Descriptor()
	// recording.DefaultCreatedAt holds the default value on creation for the created_at field.
	recording.DefaultCreatedAt = recordingDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[3].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[2].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
