// Code generated by ent, DO NOT EDIT.

package pushsubscription

import (
	"cctv/shared/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldUserID, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldEndpoint, v))
}

// P256dh applies equality check predicate on the "p256dh" field. It's identical to P256dhEQ.
func P256dh(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldP256dh, v))
}

// Auth applies equality check predicate on the "auth" field. It's identical to AuthEQ.
func Auth(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldAuth, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldUserAgent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNotNull(FieldUserID))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContainsFold(FieldUserID, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContainsFold(FieldEndpoint, v))
}

// P256dhEQ applies the EQ predicate on the "p256dh" field.
func P256dhEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldP256dh, v))
}

// P256dhNEQ applies the NEQ predicate on the "p256dh" field.
func P256dhNEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNEQ(FieldP256dh, v))
}

// P256dhIn applies the In predicate on the "p256dh" field.
func P256dhIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldIn(FieldP256dh, vs...))
}

// P256dhNotIn applies the NotIn predicate on the "p256dh" field.
func P256dhNotIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNotIn(FieldP256dh, vs...))
}

// P256dhGT applies the GT predicate on the "p256dh" field.
func P256dhGT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGT(FieldP256dh, v))
}

// P256dhGTE applies the GTE predicate on the "p256dh" field.
func P256dhGTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGTE(FieldP256dh, v))
}

// P256dhLT applies the LT predicate on the "p256dh" field.
func P256dhLT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLT(FieldP256dh, v))
}

// P256dhLTE applies the LTE predicate on the "p256dh" field.
func P256dhLTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLTE(FieldP256dh, v))
}

// P256dhContains applies the Contains predicate on the "p256dh" field.
func P256dhContains(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContains(FieldP256dh, v))
}

// P256dhHasPrefix applies the HasPrefix predicate on the "p256dh" field.
func P256dhHasPrefix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasPrefix(FieldP256dh, v))
}

// P256dhHasSuffix applies the HasSuffix predicate on the "p256dh" field.
func P256dhHasSuffix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasSuffix(FieldP256dh, v))
}

// P256dhEqualFold applies the EqualFold predicate on the "p256dh" field.
func P256dhEqualFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEqualFold(FieldP256dh, v))
}

// P256dhContainsFold applies the ContainsFold predicate on the "p256dh" field.
func P256dhContainsFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContainsFold(FieldP256dh, v))
}

// AuthEQ applies the EQ predicate on the "auth" field.
func AuthEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldAuth, v))
}

// AuthNEQ applies the NEQ predicate on the "auth" field.
func AuthNEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNEQ(FieldAuth, v))
}

// AuthIn applies the In predicate on the "auth" field.
func AuthIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldIn(FieldAuth, vs...))
}

// AuthNotIn applies the NotIn predicate on the "auth" field.
func AuthNotIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNotIn(FieldAuth, vs...))
}

// AuthGT applies the GT predicate on the "auth" field.
func AuthGT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGT(FieldAuth, v))
}

// AuthGTE applies the GTE predicate on the "auth" field.
func AuthGTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGTE(FieldAuth, v))
}

// AuthLT applies the LT predicate on the "auth" field.
func AuthLT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLT(FieldAuth, v))
}

// AuthLTE applies the LTE predicate on the "auth" field.
func AuthLTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLTE(FieldAuth, v))
}

// AuthContains applies the Contains predicate on the "auth" field.
func AuthContains(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContains(FieldAuth, v))
}

// AuthHasPrefix applies the HasPrefix predicate on the "auth" field.
func AuthHasPrefix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasPrefix(FieldAuth, v))
}

// AuthHasSuffix applies the HasSuffix predicate on the "auth" field.
func AuthHasSuffix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasSuffix(FieldAuth, v))
}

// AuthEqualFold applies the EqualFold predicate on the "auth" field.
func AuthEqualFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEqualFold(FieldAuth, v))
}

// AuthContainsFold applies the ContainsFold predicate on the "auth" field.
func AuthContainsFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContainsFold(FieldAuth, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldContainsFold(FieldUserAgent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PushSubscription {
	return predicate.PushSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PushSubscription) predicate.PushSubscription {
	return predicate.PushSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PushSubscription) predicate.PushSubscription {
	return predicate.PushSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PushSubscription) predicate.PushSubscription {
	return predicate.PushSubscription(sql.NotPredicates(p))
}
