syntax = "proto3";

package pb;
option go_package = "cctv/shared/pkg/pb";

message VerifyTokenRequest {
  string token = 1;
}

message UserData {
  string id = 1;
  string username = 2;
  string full_name = 3;
  string role = 4;
  bool is_active = 5;
}

message VerifyTokenResponse {
  bool valid = 1;
  UserData user = 2;
}

message VerifyClientRequest {
  string api_key = 1;
}

message ClientData {
  string id = 1;
  string client_id = 2;
  string name = 3;
  string platform = 4;
  bool is_active = 5;
  bool is_system = 6;
}

message VerifyClientResponse {
  bool valid = 1;
  ClientData client = 2;
  string error = 3;
}

service AuthService {
  rpc VerifyToken(VerifyTokenRequest) returns (VerifyTokenResponse);
  rpc VerifyClient(VerifyClientRequest) returns (VerifyClientResponse);
}

