// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: core.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCamerasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlyAiEnabled bool                   `protobuf:"varint,1,opt,name=only_ai_enabled,json=onlyAiEnabled,proto3" json:"only_ai_enabled,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,2,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCamerasRequest) Reset() {
	*x = GetCamerasRequest{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCamerasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCamerasRequest) ProtoMessage() {}

func (x *GetCamerasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCamerasRequest.ProtoReflect.Descriptor instead.
func (*GetCamerasRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *GetCamerasRequest) GetOnlyAiEnabled() bool {
	if x != nil {
		return x.OnlyAiEnabled
	}
	return false
}

func (x *GetCamerasRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

type CameraData struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host     string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	IsActive bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	EnableAi bool                   `protobuf:"varint,5,opt,name=enable_ai,json=enableAi,proto3" json:"enable_ai,omitempty"`
	// Opt-in ground-plane calibration (HIGH_ANGLE_VISION_STRATEGY.md §2.4).
	IsFixed          bool   `protobuf:"varint,6,opt,name=is_fixed,json=isFixed,proto3" json:"is_fixed,omitempty"`
	HomographyPoints string `protobuf:"bytes,7,opt,name=homography_points,json=homographyPoints,proto3" json:"homography_points,omitempty"` // JSON array of 4 {x,y} normalized image points
	HomographyValid  bool   `protobuf:"varint,8,opt,name=homography_valid,json=homographyValid,proto3" json:"homography_valid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CameraData) Reset() {
	*x = CameraData{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraData) ProtoMessage() {}

func (x *CameraData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraData.ProtoReflect.Descriptor instead.
func (*CameraData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *CameraData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CameraData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CameraData) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CameraData) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CameraData) GetEnableAi() bool {
	if x != nil {
		return x.EnableAi
	}
	return false
}

func (x *CameraData) GetIsFixed() bool {
	if x != nil {
		return x.IsFixed
	}
	return false
}

func (x *CameraData) GetHomographyPoints() string {
	if x != nil {
		return x.HomographyPoints
	}
	return ""
}

func (x *CameraData) GetHomographyValid() bool {
	if x != nil {
		return x.HomographyValid
	}
	return false
}

type GetCamerasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cameras       []*CameraData          `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCamerasResponse) Reset() {
	*x = GetCamerasResponse{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCamerasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCamerasResponse) ProtoMessage() {}

func (x *GetCamerasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCamerasResponse.ProtoReflect.Descriptor instead.
func (*GetCamerasResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *GetCamerasResponse) GetCameras() []*CameraData {
	if x != nil {
		return x.Cameras
	}
	return nil
}

type GetFacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacesRequest) Reset() {
	*x = GetFacesRequest{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacesRequest) ProtoMessage() {}

func (x *GetFacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacesRequest.ProtoReflect.Descriptor instead.
func (*GetFacesRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *GetFacesRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type FaceVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaceId        string                 `protobuf:"bytes,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	MemberId      string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceVector) Reset() {
	*x = FaceVector{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceVector) ProtoMessage() {}

func (x *FaceVector) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceVector.ProtoReflect.Descriptor instead.
func (*FaceVector) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *FaceVector) GetFaceId() string {
	if x != nil {
		return x.FaceId
	}
	return ""
}

func (x *FaceVector) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *FaceVector) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *FaceVector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FaceVector) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetFacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faces         []*FaceVector          `protobuf:"bytes,1,rep,name=faces,proto3" json:"faces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacesResponse) Reset() {
	*x = GetFacesResponse{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacesResponse) ProtoMessage() {}

func (x *GetFacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacesResponse.ProtoReflect.Descriptor instead.
func (*GetFacesResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *GetFacesResponse) GetFaces() []*FaceVector {
	if x != nil {
		return x.Faces
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x02pb\"\\\n" +
	"\x11GetCamerasRequest\x12&\n" +
	"\x0fonly_ai_enabled\x18\x01 \x01(\bR\ronlyAiEnabled\x12\x1f\n" +
	"\vonly_active\x18\x02 \x01(\bR\n" +
	"onlyActive\"\xf1\x01\n" +
	"\n" +
	"CameraData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1b\n" +
	"\tenable_ai\x18\x05 \x01(\bR\benableAi\x12\x19\n" +
	"\bis_fixed\x18\x06 \x01(\bR\aisFixed\x12+\n" +
	"\x11homography_points\x18\a \x01(\tR\x10homographyPoints\x12)\n" +
	"\x10homography_valid\x18\b \x01(\bR\x0fhomographyValid\">\n" +
	"\x12GetCamerasResponse\x12(\n" +
	"\acameras\x18\x01 \x03(\v2\x0e.pb.CameraDataR\acameras\".\n" +
	"\x0fGetFacesRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"\x88\x01\n" +
	"\n" +
	"FaceVector\x12\x17\n" +
	"\aface_id\x18\x01 \x01(\tR\x06faceId\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"8\n" +
	"\x10GetFacesResponse\x12$\n" +
	"\x05faces\x18\x01 \x03(\v2\x0e.pb.FaceVectorR\x05faces2\x81\x01\n" +
	"\vCoreService\x12;\n" +
	"\n" +
	"GetCameras\x12\x15.pb.GetCamerasRequest\x1a\x16.pb.GetCamerasResponse\x125\n" +
	"\bGetFaces\x12\x13.pb.GetFacesRequest\x1a\x14.pb.GetFacesResponseB\x14Z\x12cctv/shared/pkg/pbb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_proto_goTypes = []any{
	(*GetCamerasRequest)(nil),  // 0: pb.GetCamerasRequest
	(*CameraData)(nil),         // 1: pb.CameraData
	(*GetCamerasResponse)(nil), // 2: pb.GetCamerasResponse
	(*GetFacesRequest)(nil),    // 3: pb.GetFacesRequest
	(*FaceVector)(nil),         // 4: pb.FaceVector
	(*GetFacesResponse)(nil),   // 5: pb.GetFacesResponse
}
var file_core_proto_depIdxs = []int32{
	1, // 0: pb.GetCamerasResponse.cameras:type_name -> pb.CameraData
	4, // 1: pb.GetFacesResponse.faces:type_name -> pb.FaceVector
	0, // 2: pb.CoreService.GetCameras:input_type -> pb.GetCamerasRequest
	3, // 3: pb.CoreService.GetFaces:input_type -> pb.GetFacesRequest
	2, // 4: pb.CoreService.GetCameras:output_type -> pb.GetCamerasResponse
	5, // 5: pb.CoreService.GetFaces:output_type -> pb.GetFacesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
