// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: pool.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoolService_SignalWebRTC_FullMethodName        = "/pb.PoolService/SignalWebRTC"
	PoolService_ReleaseStream_FullMethodName       = "/pb.PoolService/ReleaseStream"
	PoolService_HeartbeatStream_FullMethodName     = "/pb.PoolService/HeartbeatStream"
	PoolService_ChangeStreamProfile_FullMethodName = "/pb.PoolService/ChangeStreamProfile"
	PoolService_GetStatusSummary_FullMethodName    = "/pb.PoolService/GetStatusSummary"
)

// PoolServiceClient is the client API for PoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoolServiceClient interface {
	SignalWebRTC(ctx context.Context, in *SignalWebRTCRequest, opts ...grpc.CallOption) (*SignalWebRTCResponse, error)
	ReleaseStream(ctx context.Context, in *ReleaseStreamRequest, opts ...grpc.CallOption) (*ReleaseStreamResponse, error)
	HeartbeatStream(ctx context.Context, in *HeartbeatStreamRequest, opts ...grpc.CallOption) (*HeartbeatStreamResponse, error)
	ChangeStreamProfile(ctx context.Context, in *ChangeStreamProfileRequest, opts ...grpc.CallOption) (*ChangeStreamProfileResponse, error)
	GetStatusSummary(ctx context.Context, in *GetStatusSummaryRequest, opts ...grpc.CallOption) (*GetStatusSummaryResponse, error)
}

type poolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolServiceClient(cc grpc.ClientConnInterface) PoolServiceClient {
	return &poolServiceClient{cc}
}

func (c *poolServiceClient) SignalWebRTC(ctx context.Context, in *SignalWebRTCRequest, opts ...grpc.CallOption) (*SignalWebRTCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalWebRTCResponse)
	err := c.cc.Invoke(ctx, PoolService_SignalWebRTC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) ReleaseStream(ctx context.Context, in *ReleaseStreamRequest, opts ...grpc.CallOption) (*ReleaseStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseStreamResponse)
	err := c.cc.Invoke(ctx, PoolService_ReleaseStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) HeartbeatStream(ctx context.Context, in *HeartbeatStreamRequest, opts ...grpc.CallOption) (*HeartbeatStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatStreamResponse)
	err := c.cc.Invoke(ctx, PoolService_HeartbeatStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) ChangeStreamProfile(ctx context.Context, in *ChangeStreamProfileRequest, opts ...grpc.CallOption) (*ChangeStreamProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeStreamProfileResponse)
	err := c.cc.Invoke(ctx, PoolService_ChangeStreamProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) GetStatusSummary(ctx context.Context, in *GetStatusSummaryRequest, opts ...grpc.CallOption) (*GetStatusSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusSummaryResponse)
	err := c.cc.Invoke(ctx, PoolService_GetStatusSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolServiceServer is the server API for PoolService service.
// All implementations must embed UnimplementedPoolServiceServer
// for forward compatibility.
type PoolServiceServer interface {
	SignalWebRTC(context.Context, *SignalWebRTCRequest) (*SignalWebRTCResponse, error)
	ReleaseStream(context.Context, *ReleaseStreamRequest) (*ReleaseStreamResponse, error)
	HeartbeatStream(context.Context, *HeartbeatStreamRequest) (*HeartbeatStreamResponse, error)
	ChangeStreamProfile(context.Context, *ChangeStreamProfileRequest) (*ChangeStreamProfileResponse, error)
	GetStatusSummary(context.Context, *GetStatusSummaryRequest) (*GetStatusSummaryResponse, error)
	mustEmbedUnimplementedPoolServiceServer()
}

// UnimplementedPoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolServiceServer struct{}

func (UnimplementedPoolServiceServer) SignalWebRTC(context.Context, *SignalWebRTCRequest) (*SignalWebRTCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalWebRTC not implemented")
}
func (UnimplementedPoolServiceServer) ReleaseStream(context.Context, *ReleaseStreamRequest) (*ReleaseStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseStream not implemented")
}
func (UnimplementedPoolServiceServer) HeartbeatStream(context.Context, *HeartbeatStreamRequest) (*HeartbeatStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatStream not implemented")
}
func (UnimplementedPoolServiceServer) ChangeStreamProfile(context.Context, *ChangeStreamProfileRequest) (*ChangeStreamProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeStreamProfile not implemented")
}
func (UnimplementedPoolServiceServer) GetStatusSummary(context.Context, *GetStatusSummaryRequest) (*GetStatusSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatusSummary not implemented")
}
func (UnimplementedPoolServiceServer) mustEmbedUnimplementedPoolServiceServer() {}
func (UnimplementedPoolServiceServer) testEmbeddedByValue()                     {}

// UnsafePoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolServiceServer will
// result in compilation errors.
type UnsafePoolServiceServer interface {
	mustEmbedUnimplementedPoolServiceServer()
}

func RegisterPoolServiceServer(s grpc.ServiceRegistrar, srv PoolServiceServer) {
	// If the following call pancis, it indicates UnimplementedPoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolService_ServiceDesc, srv)
}

func _PoolService_SignalWebRTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalWebRTCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).SignalWebRTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_SignalWebRTC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).SignalWebRTC(ctx, req.(*SignalWebRTCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_ReleaseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).ReleaseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_ReleaseStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).ReleaseStream(ctx, req.(*ReleaseStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_HeartbeatStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).HeartbeatStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_HeartbeatStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).HeartbeatStream(ctx, req.(*HeartbeatStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_ChangeStreamProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStreamProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).ChangeStreamProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_ChangeStreamProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).ChangeStreamProfile(ctx, req.(*ChangeStreamProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_GetStatusSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).GetStatusSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_GetStatusSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).GetStatusSummary(ctx, req.(*GetStatusSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolService_ServiceDesc is the grpc.ServiceDesc for PoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PoolService",
	HandlerType: (*PoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignalWebRTC",
			Handler:    _PoolService_SignalWebRTC_Handler,
		},
		{
			MethodName: "ReleaseStream",
			Handler:    _PoolService_ReleaseStream_Handler,
		},
		{
			MethodName: "HeartbeatStream",
			Handler:    _PoolService_HeartbeatStream_Handler,
		},
		{
			MethodName: "ChangeStreamProfile",
			Handler:    _PoolService_ChangeStreamProfile_Handler,
		},
		{
			MethodName: "GetStatusSummary",
			Handler:    _PoolService_GetStatusSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pool.proto",
}
