// Code generated by ent, DO NOT EDIT.

package camera

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the camera type in the database.
	Label = "camera"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldHost holds the string denoting the host field in the database.
	FieldHost = "host"
	// FieldBrand holds the string denoting the brand field in the database.
	FieldBrand = "brand"
	// FieldRtspPort holds the string denoting the rtsp_port field in the database.
	FieldRtspPort = "rtsp_port"
	// FieldRtspTransport holds the string denoting the rtsp_transport field in the database.
	FieldRtspTransport = "rtsp_transport"
	// FieldSegmentDuration holds the string denoting the segment_duration field in the database.
	FieldSegmentDuration = "segment_duration"
	// FieldVideoCodec holds the string denoting the video_codec field in the database.
	FieldVideoCodec = "video_codec"
	// FieldAudioMode holds the string denoting the audio_mode field in the database.
	FieldAudioMode = "audio_mode"
	// FieldExtraArgs holds the string denoting the extra_args field in the database.
	FieldExtraArgs = "extra_args"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldEnableAi holds the string denoting the enable_ai field in the database.
	FieldEnableAi = "enable_ai"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRecordings holds the string denoting the recordings edge name in mutations.
	EdgeRecordings = "recordings"
	// Table holds the table name of the camera in the database.
	Table = "cameras"
	// RecordingsTable is the table that holds the recordings relation/edge.
	RecordingsTable = "recordings"
	// RecordingsInverseTable is the table name for the Recording entity.
	// It exists in this package in order to avoid circular dependency with the "recording" package.
	RecordingsInverseTable = "recordings"
	// RecordingsColumn is the table column denoting the recordings relation/edge.
	RecordingsColumn = "camera_recordings"
)

// Columns holds all SQL columns for camera fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldHost,
	FieldBrand,
	FieldRtspPort,
	FieldRtspTransport,
	FieldSegmentDuration,
	FieldVideoCodec,
	FieldAudioMode,
	FieldExtraArgs,
	FieldIsActive,
	FieldEnableAi,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// HostValidator is a validator for the "host" field. It is called by the builders before save.
	HostValidator func(string) error
	// DefaultBrand holds the default value on creation for the "brand" field.
	DefaultBrand string
	// DefaultRtspPort holds the default value on creation for the "rtsp_port" field.
	DefaultRtspPort int
	// DefaultRtspTransport holds the default value on creation for the "rtsp_transport" field.
	DefaultRtspTransport string
	// DefaultSegmentDuration holds the default value on creation for the "segment_duration" field.
	DefaultSegmentDuration int
	// DefaultVideoCodec holds the default value on creation for the "video_codec" field.
	DefaultVideoCodec string
	// DefaultAudioMode holds the default value on creation for the "audio_mode" field.
	DefaultAudioMode string
	// DefaultExtraArgs holds the default value on creation for the "extra_args" field.
	DefaultExtraArgs string
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultEnableAi holds the default value on creation for the "enable_ai" field.
	DefaultEnableAi bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Camera queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByHost orders the results by the host field.
func ByHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHost, opts...).ToFunc()
}

// ByBrand orders the results by the brand field.
func ByBrand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrand, opts...).ToFunc()
}

// ByRtspPort orders the results by the rtsp_port field.
func ByRtspPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRtspPort, opts...).ToFunc()
}

// ByRtspTransport orders the results by the rtsp_transport field.
func ByRtspTransport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRtspTransport, opts...).ToFunc()
}

// BySegmentDuration orders the results by the segment_duration field.
func BySegmentDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSegmentDuration, opts...).ToFunc()
}

// ByVideoCodec orders the results by the video_codec field.
func ByVideoCodec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoCodec, opts...).ToFunc()
}

// ByAudioMode orders the results by the audio_mode field.
func ByAudioMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioMode, opts...).ToFunc()
}

// ByExtraArgs orders the results by the extra_args field.
func ByExtraArgs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtraArgs, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByEnableAi orders the results by the enable_ai field.
func ByEnableAi(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableAi, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRecordingsCount orders the results by recordings count.
func ByRecordingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecordingsStep(), opts...)
	}
}

// ByRecordings orders the results by recordings terms.
func ByRecordings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecordingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRecordingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecordingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecordingsTable, RecordingsColumn),
	)
}
