// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/camera"
	"cctv/shared/ent/recording"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CameraCreate is the builder for creating a Camera entity.
type CameraCreate struct {
	config
	mutation *CameraMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CameraCreate) SetName(v string) *CameraCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetHost sets the "host" field.
func (_c *CameraCreate) SetHost(v string) *CameraCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetBrand sets the "brand" field.
func (_c *CameraCreate) SetBrand(v string) *CameraCreate {
	_c.mutation.SetBrand(v)
	return _c
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_c *CameraCreate) SetNillableBrand(v *string) *CameraCreate {
	if v != nil {
		_c.SetBrand(*v)
	}
	return _c
}

// SetRtspPort sets the "rtsp_port" field.
func (_c *CameraCreate) SetRtspPort(v int) *CameraCreate {
	_c.mutation.SetRtspPort(v)
	return _c
}

// SetNillableRtspPort sets the "rtsp_port" field if the given value is not nil.
func (_c *CameraCreate) SetNillableRtspPort(v *int) *CameraCreate {
	if v != nil {
		_c.SetRtspPort(*v)
	}
	return _c
}

// SetRtspTransport sets the "rtsp_transport" field.
func (_c *CameraCreate) SetRtspTransport(v string) *CameraCreate {
	_c.mutation.SetRtspTransport(v)
	return _c
}

// SetNillableRtspTransport sets the "rtsp_transport" field if the given value is not nil.
func (_c *CameraCreate) SetNillableRtspTransport(v *string) *CameraCreate {
	if v != nil {
		_c.SetRtspTransport(*v)
	}
	return _c
}

// SetSegmentDuration sets the "segment_duration" field.
func (_c *CameraCreate) SetSegmentDuration(v int) *CameraCreate {
	_c.mutation.SetSegmentDuration(v)
	return _c
}

// SetNillableSegmentDuration sets the "segment_duration" field if the given value is not nil.
func (_c *CameraCreate) SetNillableSegmentDuration(v *int) *CameraCreate {
	if v != nil {
		_c.SetSegmentDuration(*v)
	}
	return _c
}

// SetVideoCodec sets the "video_codec" field.
func (_c *CameraCreate) SetVideoCodec(v string) *CameraCreate {
	_c.mutation.SetVideoCodec(v)
	return _c
}

// SetNillableVideoCodec sets the "video_codec" field if the given value is not nil.
func (_c *CameraCreate) SetNillableVideoCodec(v *string) *CameraCreate {
	if v != nil {
		_c.SetVideoCodec(*v)
	}
	return _c
}

// SetAudioMode sets the "audio_mode" field.
func (_c *CameraCreate) SetAudioMode(v string) *CameraCreate {
	_c.mutation.SetAudioMode(v)
	return _c
}

// SetNillableAudioMode sets the "audio_mode" field if the given value is not nil.
func (_c *CameraCreate) SetNillableAudioMode(v *string) *CameraCreate {
	if v != nil {
		_c.SetAudioMode(*v)
	}
	return _c
}

// SetExtraArgs sets the "extra_args" field.
func (_c *CameraCreate) SetExtraArgs(v string) *CameraCreate {
	_c.mutation.SetExtraArgs(v)
	return _c
}

// SetNillableExtraArgs sets the "extra_args" field if the given value is not nil.
func (_c *CameraCreate) SetNillableExtraArgs(v *string) *CameraCreate {
	if v != nil {
		_c.SetExtraArgs(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *CameraCreate) SetIsActive(v bool) *CameraCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *CameraCreate) SetNillableIsActive(v *bool) *CameraCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetEnableAi sets the "enable_ai" field.
func (_c *CameraCreate) SetEnableAi(v bool) *CameraCreate {
	_c.mutation.SetEnableAi(v)
	return _c
}

// SetNillableEnableAi sets the "enable_ai" field if the given value is not nil.
func (_c *CameraCreate) SetNillableEnableAi(v *bool) *CameraCreate {
	if v != nil {
		_c.SetEnableAi(*v)
	}
	return _c
}

// SetShowBbox sets the "show_bbox" field.
func (_c *CameraCreate) SetShowBbox(v bool) *CameraCreate {
	_c.mutation.SetShowBbox(v)
	return _c
}

// SetNillableShowBbox sets the "show_bbox" field if the given value is not nil.
func (_c *CameraCreate) SetNillableShowBbox(v *bool) *CameraCreate {
	if v != nil {
		_c.SetShowBbox(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CameraCreate) SetCreatedAt(v time.Time) *CameraCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CameraCreate) SetNillableCreatedAt(v *time.Time) *CameraCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CameraCreate) SetUpdatedAt(v time.Time) *CameraCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CameraCreate) SetNillableUpdatedAt(v *time.Time) *CameraCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CameraCreate) SetID(v string) *CameraCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CameraCreate) SetNillableID(v *string) *CameraCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddRecordingIDs adds the "recordings" edge to the Recording entity by IDs.
func (_c *CameraCreate) AddRecordingIDs(ids ...string) *CameraCreate {
	_c.mutation.AddRecordingIDs(ids...)
	return _c
}

// AddRecordings adds the "recordings" edges to the Recording entity.
func (_c *CameraCreate) AddRecordings(v ...*Recording) *CameraCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordingIDs(ids...)
}

// Mutation returns the CameraMutation object of the builder.
func (_c *CameraCreate) Mutation() *CameraMutation {
	return _c.mutation
}

// Save creates the Camera in the database.
func (_c *CameraCreate) Save(ctx context.Context) (*Camera, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CameraCreate) SaveX(ctx context.Context) *Camera {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CameraCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CameraCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CameraCreate) defaults() {
	if _, ok := _c.mutation.Brand(); !ok {
		v := camera.DefaultBrand
		_c.mutation.SetBrand(v)
	}
	if _, ok := _c.mutation.RtspPort(); !ok {
		v := camera.DefaultRtspPort
		_c.mutation.SetRtspPort(v)
	}
	if _, ok := _c.mutation.RtspTransport(); !ok {
		v := camera.DefaultRtspTransport
		_c.mutation.SetRtspTransport(v)
	}
	if _, ok := _c.mutation.SegmentDuration(); !ok {
		v := camera.DefaultSegmentDuration
		_c.mutation.SetSegmentDuration(v)
	}
	if _, ok := _c.mutation.VideoCodec(); !ok {
		v := camera.DefaultVideoCodec
		_c.mutation.SetVideoCodec(v)
	}
	if _, ok := _c.mutation.AudioMode(); !ok {
		v := camera.DefaultAudioMode
		_c.mutation.SetAudioMode(v)
	}
	if _, ok := _c.mutation.ExtraArgs(); !ok {
		v := camera.DefaultExtraArgs
		_c.mutation.SetExtraArgs(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := camera.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.EnableAi(); !ok {
		v := camera.DefaultEnableAi
		_c.mutation.SetEnableAi(v)
	}
	if _, ok := _c.mutation.ShowBbox(); !ok {
		v := camera.DefaultShowBbox
		_c.mutation.SetShowBbox(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := camera.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := camera.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := camera.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CameraCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Camera.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := camera.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Camera.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Camera.host"`)}
	}
	if v, ok := _c.mutation.Host(); ok {
		if err := camera.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Camera.host": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Brand(); !ok {
		return &ValidationError{Name: "brand", err: errors.New(`ent: missing required field "Camera.brand"`)}
	}
	if _, ok := _c.mutation.RtspPort(); !ok {
		return &ValidationError{Name: "rtsp_port", err: errors.New(`ent: missing required field "Camera.rtsp_port"`)}
	}
	if _, ok := _c.mutation.RtspTransport(); !ok {
		return &ValidationError{Name: "rtsp_transport", err: errors.New(`ent: missing required field "Camera.rtsp_transport"`)}
	}
	if _, ok := _c.mutation.SegmentDuration(); !ok {
		return &ValidationError{Name: "segment_duration", err: errors.New(`ent: missing required field "Camera.segment_duration"`)}
	}
	if _, ok := _c.mutation.VideoCodec(); !ok {
		return &ValidationError{Name: "video_codec", err: errors.New(`ent: missing required field "Camera.video_codec"`)}
	}
	if _, ok := _c.mutation.AudioMode(); !ok {
		return &ValidationError{Name: "audio_mode", err: errors.New(`ent: missing required field "Camera.audio_mode"`)}
	}
	if _, ok := _c.mutation.ExtraArgs(); !ok {
		return &ValidationError{Name: "extra_args", err: errors.New(`ent: missing required field "Camera.extra_args"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Camera.is_active"`)}
	}
	if _, ok := _c.mutation.EnableAi(); !ok {
		return &ValidationError{Name: "enable_ai", err: errors.New(`ent: missing required field "Camera.enable_ai"`)}
	}
	if _, ok := _c.mutation.ShowBbox(); !ok {
		return &ValidationError{Name: "show_bbox", err: errors.New(`ent: missing required field "Camera.show_bbox"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Camera.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Camera.updated_at"`)}
	}
	return nil
}

func (_c *CameraCreate) sqlSave(ctx context.Context) (*Camera, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Camera.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CameraCreate) createSpec() (*Camera, *sqlgraph.CreateSpec) {
	var (
		_node = &Camera{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(camera.Table, sqlgraph.NewFieldSpec(camera.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(camera.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(camera.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Brand(); ok {
		_spec.SetField(camera.FieldBrand, field.TypeString, value)
		_node.Brand = value
	}
	if value, ok := _c.mutation.RtspPort(); ok {
		_spec.SetField(camera.FieldRtspPort, field.TypeInt, value)
		_node.RtspPort = value
	}
	if value, ok := _c.mutation.RtspTransport(); ok {
		_spec.SetField(camera.FieldRtspTransport, field.TypeString, value)
		_node.RtspTransport = value
	}
	if value, ok := _c.mutation.SegmentDuration(); ok {
		_spec.SetField(camera.FieldSegmentDuration, field.TypeInt, value)
		_node.SegmentDuration = value
	}
	if value, ok := _c.mutation.VideoCodec(); ok {
		_spec.SetField(camera.FieldVideoCodec, field.TypeString, value)
		_node.VideoCodec = value
	}
	if value, ok := _c.mutation.AudioMode(); ok {
		_spec.SetField(camera.FieldAudioMode, field.TypeString, value)
		_node.AudioMode = value
	}
	if value, ok := _c.mutation.ExtraArgs(); ok {
		_spec.SetField(camera.FieldExtraArgs, field.TypeString, value)
		_node.ExtraArgs = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(camera.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.EnableAi(); ok {
		_spec.SetField(camera.FieldEnableAi, field.TypeBool, value)
		_node.EnableAi = value
	}
	if value, ok := _c.mutation.ShowBbox(); ok {
		_spec.SetField(camera.FieldShowBbox, field.TypeBool, value)
		_node.ShowBbox = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(camera.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(camera.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RecordingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   camera.RecordingsTable,
			Columns: []string{camera.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CameraCreateBulk is the builder for creating many Camera entities in bulk.
type CameraCreateBulk struct {
	config
	err      error
	builders []*CameraCreate
}

// Save creates the Camera entities in the database.
func (_c *CameraCreateBulk) Save(ctx context.Context) ([]*Camera, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Camera, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CameraMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CameraCreateBulk) SaveX(ctx context.Context) []*Camera {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CameraCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CameraCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
