// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/camera"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Camera is the model entity for the Camera schema.
type Camera struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Host holds the value of the "host" field.
	Host string `json:"host,omitempty"`
	// Brand holds the value of the "brand" field.
	Brand string `json:"brand,omitempty"`
	// RtspPort holds the value of the "rtsp_port" field.
	RtspPort int `json:"rtsp_port,omitempty"`
	// RtspTransport holds the value of the "rtsp_transport" field.
	RtspTransport string `json:"rtsp_transport,omitempty"`
	// SegmentDuration holds the value of the "segment_duration" field.
	SegmentDuration int `json:"segment_duration,omitempty"`
	// VideoCodec holds the value of the "video_codec" field.
	VideoCodec string `json:"video_codec,omitempty"`
	// AudioMode holds the value of the "audio_mode" field.
	AudioMode string `json:"audio_mode,omitempty"`
	// ExtraArgs holds the value of the "extra_args" field.
	ExtraArgs string `json:"extra_args,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// EnableAi holds the value of the "enable_ai" field.
	EnableAi bool `json:"enable_ai,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CameraQuery when eager-loading is set.
	Edges        CameraEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CameraEdges holds the relations/edges for other nodes in the graph.
type CameraEdges struct {
	// Recordings holds the value of the recordings edge.
	Recordings []*Recording `json:"recordings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RecordingsOrErr returns the Recordings value or an error if the edge
// was not loaded in eager-loading.
func (e CameraEdges) RecordingsOrErr() ([]*Recording, error) {
	if e.loadedTypes[0] {
		return e.Recordings, nil
	}
	return nil, &NotLoadedError{edge: "recordings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Camera) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case camera.FieldIsActive, camera.FieldEnableAi:
			values[i] = new(sql.NullBool)
		case camera.FieldRtspPort, camera.FieldSegmentDuration:
			values[i] = new(sql.NullInt64)
		case camera.FieldID, camera.FieldName, camera.FieldHost, camera.FieldBrand, camera.FieldRtspTransport, camera.FieldVideoCodec, camera.FieldAudioMode, camera.FieldExtraArgs:
			values[i] = new(sql.NullString)
		case camera.FieldCreatedAt, camera.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Camera fields.
func (_m *Camera) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case camera.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case camera.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case camera.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case camera.FieldBrand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand", values[i])
			} else if value.Valid {
				_m.Brand = value.String
			}
		case camera.FieldRtspPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rtsp_port", values[i])
			} else if value.Valid {
				_m.RtspPort = int(value.Int64)
			}
		case camera.FieldRtspTransport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rtsp_transport", values[i])
			} else if value.Valid {
				_m.RtspTransport = value.String
			}
		case camera.FieldSegmentDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field segment_duration", values[i])
			} else if value.Valid {
				_m.SegmentDuration = int(value.Int64)
			}
		case camera.FieldVideoCodec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_codec", values[i])
			} else if value.Valid {
				_m.VideoCodec = value.String
			}
		case camera.FieldAudioMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audio_mode", values[i])
			} else if value.Valid {
				_m.AudioMode = value.String
			}
		case camera.FieldExtraArgs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra_args", values[i])
			} else if value.Valid {
				_m.ExtraArgs = value.String
			}
		case camera.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case camera.FieldEnableAi:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_ai", values[i])
			} else if value.Valid {
				_m.EnableAi = value.Bool
			}
		case camera.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case camera.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Camera.
// This includes values selected through modifiers, order, etc.
func (_m *Camera) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecordings queries the "recordings" edge of the Camera entity.
func (_m *Camera) QueryRecordings() *RecordingQuery {
	return NewCameraClient(_m.config).QueryRecordings(_m)
}

// Update returns a builder for updating this Camera.
// Note that you need to call Camera.Unwrap() before calling this method if this Camera
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Camera) Update() *CameraUpdateOne {
	return NewCameraClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Camera entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Camera) Unwrap() *Camera {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Camera is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Camera) String() string {
	var builder strings.Builder
	builder.WriteString("Camera(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("brand=")
	builder.WriteString(_m.Brand)
	builder.WriteString(", ")
	builder.WriteString("rtsp_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.RtspPort))
	builder.WriteString(", ")
	builder.WriteString("rtsp_transport=")
	builder.WriteString(_m.RtspTransport)
	builder.WriteString(", ")
	builder.WriteString("segment_duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.SegmentDuration))
	builder.WriteString(", ")
	builder.WriteString("video_codec=")
	builder.WriteString(_m.VideoCodec)
	builder.WriteString(", ")
	builder.WriteString("audio_mode=")
	builder.WriteString(_m.AudioMode)
	builder.WriteString(", ")
	builder.WriteString("extra_args=")
	builder.WriteString(_m.ExtraArgs)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("enable_ai=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnableAi))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Cameras is a parsable slice of Camera.
type Cameras []*Camera
