// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/member"
	"cctv/shared/ent/memberface"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberFaceCreate is the builder for creating a MemberFace entity.
type MemberFaceCreate struct {
	config
	mutation *MemberFaceMutation
	hooks    []Hook
}

// SetMemberID sets the "member_id" field.
func (_c *MemberFaceCreate) SetMemberID(v string) *MemberFaceCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *MemberFaceCreate) SetEmbedding(v []float64) *MemberFaceCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetSampleImageURL sets the "sample_image_url" field.
func (_c *MemberFaceCreate) SetSampleImageURL(v string) *MemberFaceCreate {
	_c.mutation.SetSampleImageURL(v)
	return _c
}

// SetNillableSampleImageURL sets the "sample_image_url" field if the given value is not nil.
func (_c *MemberFaceCreate) SetNillableSampleImageURL(v *string) *MemberFaceCreate {
	if v != nil {
		_c.SetSampleImageURL(*v)
	}
	return _c
}

// SetQualityScore sets the "quality_score" field.
func (_c *MemberFaceCreate) SetQualityScore(v float64) *MemberFaceCreate {
	_c.mutation.SetQualityScore(v)
	return _c
}

// SetNillableQualityScore sets the "quality_score" field if the given value is not nil.
func (_c *MemberFaceCreate) SetNillableQualityScore(v *float64) *MemberFaceCreate {
	if v != nil {
		_c.SetQualityScore(*v)
	}
	return _c
}

// SetYaw sets the "yaw" field.
func (_c *MemberFaceCreate) SetYaw(v float64) *MemberFaceCreate {
	_c.mutation.SetYaw(v)
	return _c
}

// SetNillableYaw sets the "yaw" field if the given value is not nil.
func (_c *MemberFaceCreate) SetNillableYaw(v *float64) *MemberFaceCreate {
	if v != nil {
		_c.SetYaw(*v)
	}
	return _c
}

// SetPitch sets the "pitch" field.
func (_c *MemberFaceCreate) SetPitch(v float64) *MemberFaceCreate {
	_c.mutation.SetPitch(v)
	return _c
}

// SetNillablePitch sets the "pitch" field if the given value is not nil.
func (_c *MemberFaceCreate) SetNillablePitch(v *float64) *MemberFaceCreate {
	if v != nil {
		_c.SetPitch(*v)
	}
	return _c
}

// SetBlurScore sets the "blur_score" field.
func (_c *MemberFaceCreate) SetBlurScore(v float64) *MemberFaceCreate {
	_c.mutation.SetBlurScore(v)
	return _c
}

// SetNillableBlurScore sets the "blur_score" field if the given value is not nil.
func (_c *MemberFaceCreate) SetNillableBlurScore(v *float64) *MemberFaceCreate {
	if v != nil {
		_c.SetBlurScore(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *MemberFaceCreate) SetIsActive(v bool) *MemberFaceCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *MemberFaceCreate) SetNillableIsActive(v *bool) *MemberFaceCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemberFaceCreate) SetCreatedAt(v time.Time) *MemberFaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemberFaceCreate) SetNillableCreatedAt(v *time.Time) *MemberFaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MemberFaceCreate) SetID(v string) *MemberFaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MemberFaceCreate) SetNillableID(v *string) *MemberFaceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetMember sets the "member" edge to the Member entity.
func (_c *MemberFaceCreate) SetMember(v *Member) *MemberFaceCreate {
	return _c.SetMemberID(v.ID)
}

// Mutation returns the MemberFaceMutation object of the builder.
func (_c *MemberFaceCreate) Mutation() *MemberFaceMutation {
	return _c.mutation
}

// Save creates the MemberFace in the database.
func (_c *MemberFaceCreate) Save(ctx context.Context) (*MemberFace, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberFaceCreate) SaveX(ctx context.Context) *MemberFace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberFaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberFaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberFaceCreate) defaults() {
	if _, ok := _c.mutation.SampleImageURL(); !ok {
		v := memberface.DefaultSampleImageURL
		_c.mutation.SetSampleImageURL(v)
	}
	if _, ok := _c.mutation.QualityScore(); !ok {
		v := memberface.DefaultQualityScore
		_c.mutation.SetQualityScore(v)
	}
	if _, ok := _c.mutation.Yaw(); !ok {
		v := memberface.DefaultYaw
		_c.mutation.SetYaw(v)
	}
	if _, ok := _c.mutation.Pitch(); !ok {
		v := memberface.DefaultPitch
		_c.mutation.SetPitch(v)
	}
	if _, ok := _c.mutation.BlurScore(); !ok {
		v := memberface.DefaultBlurScore
		_c.mutation.SetBlurScore(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := memberface.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memberface.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := memberface.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberFaceCreate) check() error {
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "MemberFace.member_id"`)}
	}
	if _, ok := _c.mutation.Embedding(); !ok {
		return &ValidationError{Name: "embedding", err: errors.New(`ent: missing required field "MemberFace.embedding"`)}
	}
	if _, ok := _c.mutation.SampleImageURL(); !ok {
		return &ValidationError{Name: "sample_image_url", err: errors.New(`ent: missing required field "MemberFace.sample_image_url"`)}
	}
	if _, ok := _c.mutation.QualityScore(); !ok {
		return &ValidationError{Name: "quality_score", err: errors.New(`ent: missing required field "MemberFace.quality_score"`)}
	}
	if _, ok := _c.mutation.Yaw(); !ok {
		return &ValidationError{Name: "yaw", err: errors.New(`ent: missing required field "MemberFace.yaw"`)}
	}
	if _, ok := _c.mutation.Pitch(); !ok {
		return &ValidationError{Name: "pitch", err: errors.New(`ent: missing required field "MemberFace.pitch"`)}
	}
	if _, ok := _c.mutation.BlurScore(); !ok {
		return &ValidationError{Name: "blur_score", err: errors.New(`ent: missing required field "MemberFace.blur_score"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "MemberFace.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MemberFace.created_at"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "MemberFace.member"`)}
	}
	return nil
}

func (_c *MemberFaceCreate) sqlSave(ctx context.Context) (*MemberFace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected MemberFace.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberFaceCreate) createSpec() (*MemberFace, *sqlgraph.CreateSpec) {
	var (
		_node = &MemberFace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memberface.Table, sqlgraph.NewFieldSpec(memberface.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(memberface.FieldEmbedding, field.TypeJSON, value)
		_node.Embedding = value
	}
	if value, ok := _c.mutation.SampleImageURL(); ok {
		_spec.SetField(memberface.FieldSampleImageURL, field.TypeString, value)
		_node.SampleImageURL = value
	}
	if value, ok := _c.mutation.QualityScore(); ok {
		_spec.SetField(memberface.FieldQualityScore, field.TypeFloat64, value)
		_node.QualityScore = value
	}
	if value, ok := _c.mutation.Yaw(); ok {
		_spec.SetField(memberface.FieldYaw, field.TypeFloat64, value)
		_node.Yaw = value
	}
	if value, ok := _c.mutation.Pitch(); ok {
		_spec.SetField(memberface.FieldPitch, field.TypeFloat64, value)
		_node.Pitch = value
	}
	if value, ok := _c.mutation.BlurScore(); ok {
		_spec.SetField(memberface.FieldBlurScore, field.TypeFloat64, value)
		_node.BlurScore = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(memberface.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memberface.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberface.MemberTable,
			Columns: []string{memberface.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberFaceCreateBulk is the builder for creating many MemberFace entities in bulk.
type MemberFaceCreateBulk struct {
	config
	err      error
	builders []*MemberFaceCreate
}

// Save creates the MemberFace entities in the database.
func (_c *MemberFaceCreateBulk) Save(ctx context.Context) ([]*MemberFace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemberFace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberFaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberFaceCreateBulk) SaveX(ctx context.Context) []*MemberFace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberFaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberFaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
