// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/memberface"
	"cctv/shared/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// MemberFaceUpdate is the builder for updating MemberFace entities.
type MemberFaceUpdate struct {
	config
	hooks    []Hook
	mutation *MemberFaceMutation
}

// Where appends a list predicates to the MemberFaceUpdate builder.
func (_u *MemberFaceUpdate) Where(ps ...predicate.MemberFace) *MemberFaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *MemberFaceUpdate) SetEmbedding(v []float64) *MemberFaceUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *MemberFaceUpdate) AppendEmbedding(v []float64) *MemberFaceUpdate {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// SetSampleImageURL sets the "sample_image_url" field.
func (_u *MemberFaceUpdate) SetSampleImageURL(v string) *MemberFaceUpdate {
	_u.mutation.SetSampleImageURL(v)
	return _u
}

// SetNillableSampleImageURL sets the "sample_image_url" field if the given value is not nil.
func (_u *MemberFaceUpdate) SetNillableSampleImageURL(v *string) *MemberFaceUpdate {
	if v != nil {
		_u.SetSampleImageURL(*v)
	}
	return _u
}

// SetQualityScore sets the "quality_score" field.
func (_u *MemberFaceUpdate) SetQualityScore(v float64) *MemberFaceUpdate {
	_u.mutation.ResetQualityScore()
	_u.mutation.SetQualityScore(v)
	return _u
}

// SetNillableQualityScore sets the "quality_score" field if the given value is not nil.
func (_u *MemberFaceUpdate) SetNillableQualityScore(v *float64) *MemberFaceUpdate {
	if v != nil {
		_u.SetQualityScore(*v)
	}
	return _u
}

// AddQualityScore adds value to the "quality_score" field.
func (_u *MemberFaceUpdate) AddQualityScore(v float64) *MemberFaceUpdate {
	_u.mutation.AddQualityScore(v)
	return _u
}

// SetYaw sets the "yaw" field.
func (_u *MemberFaceUpdate) SetYaw(v float64) *MemberFaceUpdate {
	_u.mutation.ResetYaw()
	_u.mutation.SetYaw(v)
	return _u
}

// SetNillableYaw sets the "yaw" field if the given value is not nil.
func (_u *MemberFaceUpdate) SetNillableYaw(v *float64) *MemberFaceUpdate {
	if v != nil {
		_u.SetYaw(*v)
	}
	return _u
}

// AddYaw adds value to the "yaw" field.
func (_u *MemberFaceUpdate) AddYaw(v float64) *MemberFaceUpdate {
	_u.mutation.AddYaw(v)
	return _u
}

// SetPitch sets the "pitch" field.
func (_u *MemberFaceUpdate) SetPitch(v float64) *MemberFaceUpdate {
	_u.mutation.ResetPitch()
	_u.mutation.SetPitch(v)
	return _u
}

// SetNillablePitch sets the "pitch" field if the given value is not nil.
func (_u *MemberFaceUpdate) SetNillablePitch(v *float64) *MemberFaceUpdate {
	if v != nil {
		_u.SetPitch(*v)
	}
	return _u
}

// AddPitch adds value to the "pitch" field.
func (_u *MemberFaceUpdate) AddPitch(v float64) *MemberFaceUpdate {
	_u.mutation.AddPitch(v)
	return _u
}

// SetBlurScore sets the "blur_score" field.
func (_u *MemberFaceUpdate) SetBlurScore(v float64) *MemberFaceUpdate {
	_u.mutation.ResetBlurScore()
	_u.mutation.SetBlurScore(v)
	return _u
}

// SetNillableBlurScore sets the "blur_score" field if the given value is not nil.
func (_u *MemberFaceUpdate) SetNillableBlurScore(v *float64) *MemberFaceUpdate {
	if v != nil {
		_u.SetBlurScore(*v)
	}
	return _u
}

// AddBlurScore adds value to the "blur_score" field.
func (_u *MemberFaceUpdate) AddBlurScore(v float64) *MemberFaceUpdate {
	_u.mutation.AddBlurScore(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *MemberFaceUpdate) SetIsActive(v bool) *MemberFaceUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *MemberFaceUpdate) SetNillableIsActive(v *bool) *MemberFaceUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MemberFaceUpdate) SetCreatedAt(v time.Time) *MemberFaceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MemberFaceUpdate) SetNillableCreatedAt(v *time.Time) *MemberFaceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MemberFaceMutation object of the builder.
func (_u *MemberFaceUpdate) Mutation() *MemberFaceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberFaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberFaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberFaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberFaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberFaceUpdate) check() error {
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberFace.member"`)
	}
	return nil
}

func (_u *MemberFaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberface.Table, memberface.Columns, sqlgraph.NewFieldSpec(memberface.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(memberface.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memberface.FieldEmbedding, value)
		})
	}
	if value, ok := _u.mutation.SampleImageURL(); ok {
		_spec.SetField(memberface.FieldSampleImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.QualityScore(); ok {
		_spec.SetField(memberface.FieldQualityScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQualityScore(); ok {
		_spec.AddField(memberface.FieldQualityScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Yaw(); ok {
		_spec.SetField(memberface.FieldYaw, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedYaw(); ok {
		_spec.AddField(memberface.FieldYaw, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pitch(); ok {
		_spec.SetField(memberface.FieldPitch, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPitch(); ok {
		_spec.AddField(memberface.FieldPitch, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BlurScore(); ok {
		_spec.SetField(memberface.FieldBlurScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBlurScore(); ok {
		_spec.AddField(memberface.FieldBlurScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(memberface.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(memberface.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberface.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberFaceUpdateOne is the builder for updating a single MemberFace entity.
type MemberFaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberFaceMutation
}

// SetEmbedding sets the "embedding" field.
func (_u *MemberFaceUpdateOne) SetEmbedding(v []float64) *MemberFaceUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *MemberFaceUpdateOne) AppendEmbedding(v []float64) *MemberFaceUpdateOne {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// SetSampleImageURL sets the "sample_image_url" field.
func (_u *MemberFaceUpdateOne) SetSampleImageURL(v string) *MemberFaceUpdateOne {
	_u.mutation.SetSampleImageURL(v)
	return _u
}

// SetNillableSampleImageURL sets the "sample_image_url" field if the given value is not nil.
func (_u *MemberFaceUpdateOne) SetNillableSampleImageURL(v *string) *MemberFaceUpdateOne {
	if v != nil {
		_u.SetSampleImageURL(*v)
	}
	return _u
}

// SetQualityScore sets the "quality_score" field.
func (_u *MemberFaceUpdateOne) SetQualityScore(v float64) *MemberFaceUpdateOne {
	_u.mutation.ResetQualityScore()
	_u.mutation.SetQualityScore(v)
	return _u
}

// SetNillableQualityScore sets the "quality_score" field if the given value is not nil.
func (_u *MemberFaceUpdateOne) SetNillableQualityScore(v *float64) *MemberFaceUpdateOne {
	if v != nil {
		_u.SetQualityScore(*v)
	}
	return _u
}

// AddQualityScore adds value to the "quality_score" field.
func (_u *MemberFaceUpdateOne) AddQualityScore(v float64) *MemberFaceUpdateOne {
	_u.mutation.AddQualityScore(v)
	return _u
}

// SetYaw sets the "yaw" field.
func (_u *MemberFaceUpdateOne) SetYaw(v float64) *MemberFaceUpdateOne {
	_u.mutation.ResetYaw()
	_u.mutation.SetYaw(v)
	return _u
}

// SetNillableYaw sets the "yaw" field if the given value is not nil.
func (_u *MemberFaceUpdateOne) SetNillableYaw(v *float64) *MemberFaceUpdateOne {
	if v != nil {
		_u.SetYaw(*v)
	}
	return _u
}

// AddYaw adds value to the "yaw" field.
func (_u *MemberFaceUpdateOne) AddYaw(v float64) *MemberFaceUpdateOne {
	_u.mutation.AddYaw(v)
	return _u
}

// SetPitch sets the "pitch" field.
func (_u *MemberFaceUpdateOne) SetPitch(v float64) *MemberFaceUpdateOne {
	_u.mutation.ResetPitch()
	_u.mutation.SetPitch(v)
	return _u
}

// SetNillablePitch sets the "pitch" field if the given value is not nil.
func (_u *MemberFaceUpdateOne) SetNillablePitch(v *float64) *MemberFaceUpdateOne {
	if v != nil {
		_u.SetPitch(*v)
	}
	return _u
}

// AddPitch adds value to the "pitch" field.
func (_u *MemberFaceUpdateOne) AddPitch(v float64) *MemberFaceUpdateOne {
	_u.mutation.AddPitch(v)
	return _u
}

// SetBlurScore sets the "blur_score" field.
func (_u *MemberFaceUpdateOne) SetBlurScore(v float64) *MemberFaceUpdateOne {
	_u.mutation.ResetBlurScore()
	_u.mutation.SetBlurScore(v)
	return _u
}

// SetNillableBlurScore sets the "blur_score" field if the given value is not nil.
func (_u *MemberFaceUpdateOne) SetNillableBlurScore(v *float64) *MemberFaceUpdateOne {
	if v != nil {
		_u.SetBlurScore(*v)
	}
	return _u
}

// AddBlurScore adds value to the "blur_score" field.
func (_u *MemberFaceUpdateOne) AddBlurScore(v float64) *MemberFaceUpdateOne {
	_u.mutation.AddBlurScore(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *MemberFaceUpdateOne) SetIsActive(v bool) *MemberFaceUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *MemberFaceUpdateOne) SetNillableIsActive(v *bool) *MemberFaceUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MemberFaceUpdateOne) SetCreatedAt(v time.Time) *MemberFaceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MemberFaceUpdateOne) SetNillableCreatedAt(v *time.Time) *MemberFaceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MemberFaceMutation object of the builder.
func (_u *MemberFaceUpdateOne) Mutation() *MemberFaceMutation {
	return _u.mutation
}

// Where appends a list predicates to the MemberFaceUpdate builder.
func (_u *MemberFaceUpdateOne) Where(ps ...predicate.MemberFace) *MemberFaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberFaceUpdateOne) Select(field string, fields ...string) *MemberFaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberFace entity.
func (_u *MemberFaceUpdateOne) Save(ctx context.Context) (*MemberFace, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberFaceUpdateOne) SaveX(ctx context.Context) *MemberFace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberFaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberFaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberFaceUpdateOne) check() error {
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberFace.member"`)
	}
	return nil
}

func (_u *MemberFaceUpdateOne) sqlSave(ctx context.Context) (_node *MemberFace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberface.Table, memberface.Columns, sqlgraph.NewFieldSpec(memberface.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberFace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberface.FieldID)
		for _, f := range fields {
			if !memberface.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memberface.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(memberface.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memberface.FieldEmbedding, value)
		})
	}
	if value, ok := _u.mutation.SampleImageURL(); ok {
		_spec.SetField(memberface.FieldSampleImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.QualityScore(); ok {
		_spec.SetField(memberface.FieldQualityScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQualityScore(); ok {
		_spec.AddField(memberface.FieldQualityScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Yaw(); ok {
		_spec.SetField(memberface.FieldYaw, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedYaw(); ok {
		_spec.AddField(memberface.FieldYaw, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pitch(); ok {
		_spec.SetField(memberface.FieldPitch, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPitch(); ok {
		_spec.AddField(memberface.FieldPitch, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BlurScore(); ok {
		_spec.SetField(memberface.FieldBlurScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBlurScore(); ok {
		_spec.AddField(memberface.FieldBlurScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(memberface.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(memberface.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &MemberFace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberface.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
