// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/notification"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetCameraID sets the "camera_id" field.
func (_c *NotificationCreate) SetCameraID(v string) *NotificationCreate {
	_c.mutation.SetCameraID(v)
	return _c
}

// SetNillableCameraID sets the "camera_id" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCameraID(v *string) *NotificationCreate {
	if v != nil {
		_c.SetCameraID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *NotificationCreate) SetType(v string) *NotificationCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableType(v *string) *NotificationCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *NotificationCreate) SetTitle(v string) *NotificationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *NotificationCreate) SetBody(v string) *NotificationCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableBody(v *string) *NotificationCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *NotificationCreate) SetCategory(v string) *NotificationCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCategory(v *string) *NotificationCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetMemberID sets the "member_id" field.
func (_c *NotificationCreate) SetMemberID(v string) *NotificationCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableMemberID(v *string) *NotificationCreate {
	if v != nil {
		_c.SetMemberID(*v)
	}
	return _c
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_c *NotificationCreate) SetThumbnailURL(v string) *NotificationCreate {
	_c.mutation.SetThumbnailURL(v)
	return _c
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableThumbnailURL(v *string) *NotificationCreate {
	if v != nil {
		_c.SetThumbnailURL(*v)
	}
	return _c
}

// SetIsRead sets the "is_read" field.
func (_c *NotificationCreate) SetIsRead(v bool) *NotificationCreate {
	_c.mutation.SetIsRead(v)
	return _c
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableIsRead(v *bool) *NotificationCreate {
	if v != nil {
		_c.SetIsRead(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationCreate) SetCreatedAt(v time.Time) *NotificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCreatedAt(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationCreate) SetID(v string) *NotificationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableID(v *string) *NotificationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NotificationMutation object of the builder.
func (_c *NotificationCreate) Mutation() *NotificationMutation {
	return _c.mutation
}

// Save creates the Notification in the database.
func (_c *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationCreate) defaults() {
	if _, ok := _c.mutation.CameraID(); !ok {
		v := notification.DefaultCameraID
		_c.mutation.SetCameraID(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := notification.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Body(); !ok {
		v := notification.DefaultBody
		_c.mutation.SetBody(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := notification.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.MemberID(); !ok {
		v := notification.DefaultMemberID
		_c.mutation.SetMemberID(v)
	}
	if _, ok := _c.mutation.ThumbnailURL(); !ok {
		v := notification.DefaultThumbnailURL
		_c.mutation.SetThumbnailURL(v)
	}
	if _, ok := _c.mutation.IsRead(); !ok {
		v := notification.DefaultIsRead
		_c.mutation.SetIsRead(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notification.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notification.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Notification.type"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Notification.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Notification.body"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Notification.category"`)}
	}
	if _, ok := _c.mutation.ThumbnailURL(); !ok {
		return &ValidationError{Name: "thumbnail_url", err: errors.New(`ent: missing required field "Notification.thumbnail_url"`)}
	}
	if _, ok := _c.mutation.IsRead(); !ok {
		return &ValidationError{Name: "is_read", err: errors.New(`ent: missing required field "Notification.is_read"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Notification.created_at"`)}
	}
	return nil
}

func (_c *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Notification.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CameraID(); ok {
		_spec.SetField(notification.FieldCameraID, field.TypeString, value)
		_node.CameraID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(notification.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.MemberID(); ok {
		_spec.SetField(notification.FieldMemberID, field.TypeString, value)
		_node.MemberID = value
	}
	if value, ok := _c.mutation.ThumbnailURL(); ok {
		_spec.SetField(notification.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = value
	}
	if value, ok := _c.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
		_node.IsRead = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (_c *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Notification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
