// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/notification"
	"cctv/shared/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCameraID sets the "camera_id" field.
func (_u *NotificationUpdate) SetCameraID(v string) *NotificationUpdate {
	_u.mutation.SetCameraID(v)
	return _u
}

// SetNillableCameraID sets the "camera_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCameraID(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetCameraID(*v)
	}
	return _u
}

// ClearCameraID clears the value of the "camera_id" field.
func (_u *NotificationUpdate) ClearCameraID() *NotificationUpdate {
	_u.mutation.ClearCameraID()
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdate) SetType(v string) *NotificationUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableType(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *NotificationUpdate) SetBody(v string) *NotificationUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableBody(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *NotificationUpdate) SetCategory(v string) *NotificationUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCategory(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *NotificationUpdate) SetMemberID(v string) *NotificationUpdate {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMemberID(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// ClearMemberID clears the value of the "member_id" field.
func (_u *NotificationUpdate) ClearMemberID() *NotificationUpdate {
	_u.mutation.ClearMemberID()
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *NotificationUpdate) SetThumbnailURL(v string) *NotificationUpdate {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableThumbnailURL(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdate) SetIsRead(v bool) *NotificationUpdate {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableIsRead(v *bool) *NotificationUpdate {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationUpdate) SetCreatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCreatedAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CameraID(); ok {
		_spec.SetField(notification.FieldCameraID, field.TypeString, value)
	}
	if _u.mutation.CameraIDCleared() {
		_spec.ClearField(notification.FieldCameraID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(notification.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(notification.FieldMemberID, field.TypeString, value)
	}
	if _u.mutation.MemberIDCleared() {
		_spec.ClearField(notification.FieldMemberID, field.TypeString)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(notification.FieldThumbnailURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetCameraID sets the "camera_id" field.
func (_u *NotificationUpdateOne) SetCameraID(v string) *NotificationUpdateOne {
	_u.mutation.SetCameraID(v)
	return _u
}

// SetNillableCameraID sets the "camera_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCameraID(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetCameraID(*v)
	}
	return _u
}

// ClearCameraID clears the value of the "camera_id" field.
func (_u *NotificationUpdateOne) ClearCameraID() *NotificationUpdateOne {
	_u.mutation.ClearCameraID()
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdateOne) SetType(v string) *NotificationUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableType(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *NotificationUpdateOne) SetBody(v string) *NotificationUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableBody(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *NotificationUpdateOne) SetCategory(v string) *NotificationUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCategory(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *NotificationUpdateOne) SetMemberID(v string) *NotificationUpdateOne {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMemberID(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// ClearMemberID clears the value of the "member_id" field.
func (_u *NotificationUpdateOne) ClearMemberID() *NotificationUpdateOne {
	_u.mutation.ClearMemberID()
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *NotificationUpdateOne) SetThumbnailURL(v string) *NotificationUpdateOne {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableThumbnailURL(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdateOne) SetIsRead(v bool) *NotificationUpdateOne {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableIsRead(v *bool) *NotificationUpdateOne {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationUpdateOne) SetCreatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCreatedAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CameraID(); ok {
		_spec.SetField(notification.FieldCameraID, field.TypeString, value)
	}
	if _u.mutation.CameraIDCleared() {
		_spec.ClearField(notification.FieldCameraID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(notification.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(notification.FieldMemberID, field.TypeString, value)
	}
	if _u.mutation.MemberIDCleared() {
		_spec.ClearField(notification.FieldMemberID, field.TypeString)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(notification.FieldThumbnailURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
