// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/recognitionlog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecognitionLogCreate is the builder for creating a RecognitionLog entity.
type RecognitionLogCreate struct {
	config
	mutation *RecognitionLogMutation
	hooks    []Hook
}

// SetCameraID sets the "camera_id" field.
func (_c *RecognitionLogCreate) SetCameraID(v string) *RecognitionLogCreate {
	_c.mutation.SetCameraID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *RecognitionLogCreate) SetType(v string) *RecognitionLogCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *RecognitionLogCreate) SetCategory(v string) *RecognitionLogCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *RecognitionLogCreate) SetNillableCategory(v *string) *RecognitionLogCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetMemberID sets the "member_id" field.
func (_c *RecognitionLogCreate) SetMemberID(v string) *RecognitionLogCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_c *RecognitionLogCreate) SetNillableMemberID(v *string) *RecognitionLogCreate {
	if v != nil {
		_c.SetMemberID(*v)
	}
	return _c
}

// SetTrackID sets the "track_id" field.
func (_c *RecognitionLogCreate) SetTrackID(v int) *RecognitionLogCreate {
	_c.mutation.SetTrackID(v)
	return _c
}

// SetNillableTrackID sets the "track_id" field if the given value is not nil.
func (_c *RecognitionLogCreate) SetNillableTrackID(v *int) *RecognitionLogCreate {
	if v != nil {
		_c.SetTrackID(*v)
	}
	return _c
}

// SetMessageKey sets the "message_key" field.
func (_c *RecognitionLogCreate) SetMessageKey(v string) *RecognitionLogCreate {
	_c.mutation.SetMessageKey(v)
	return _c
}

// SetMessageParams sets the "message_params" field.
func (_c *RecognitionLogCreate) SetMessageParams(v map[string]string) *RecognitionLogCreate {
	_c.mutation.SetMessageParams(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecognitionLogCreate) SetCreatedAt(v time.Time) *RecognitionLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecognitionLogCreate) SetNillableCreatedAt(v *time.Time) *RecognitionLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RecognitionLogCreate) SetID(v string) *RecognitionLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RecognitionLogCreate) SetNillableID(v *string) *RecognitionLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RecognitionLogMutation object of the builder.
func (_c *RecognitionLogCreate) Mutation() *RecognitionLogMutation {
	return _c.mutation
}

// Save creates the RecognitionLog in the database.
func (_c *RecognitionLogCreate) Save(ctx context.Context) (*RecognitionLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecognitionLogCreate) SaveX(ctx context.Context) *RecognitionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecognitionLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecognitionLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecognitionLogCreate) defaults() {
	if _, ok := _c.mutation.Category(); !ok {
		v := recognitionlog.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.MemberID(); !ok {
		v := recognitionlog.DefaultMemberID
		_c.mutation.SetMemberID(v)
	}
	if _, ok := _c.mutation.TrackID(); !ok {
		v := recognitionlog.DefaultTrackID
		_c.mutation.SetTrackID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := recognitionlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := recognitionlog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecognitionLogCreate) check() error {
	if _, ok := _c.mutation.CameraID(); !ok {
		return &ValidationError{Name: "camera_id", err: errors.New(`ent: missing required field "RecognitionLog.camera_id"`)}
	}
	if v, ok := _c.mutation.CameraID(); ok {
		if err := recognitionlog.CameraIDValidator(v); err != nil {
			return &ValidationError{Name: "camera_id", err: fmt.Errorf(`ent: validator failed for field "RecognitionLog.camera_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "RecognitionLog.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := recognitionlog.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RecognitionLog.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "RecognitionLog.category"`)}
	}
	if _, ok := _c.mutation.MessageKey(); !ok {
		return &ValidationError{Name: "message_key", err: errors.New(`ent: missing required field "RecognitionLog.message_key"`)}
	}
	if v, ok := _c.mutation.MessageKey(); ok {
		if err := recognitionlog.MessageKeyValidator(v); err != nil {
			return &ValidationError{Name: "message_key", err: fmt.Errorf(`ent: validator failed for field "RecognitionLog.message_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecognitionLog.created_at"`)}
	}
	return nil
}

func (_c *RecognitionLogCreate) sqlSave(ctx context.Context) (*RecognitionLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RecognitionLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecognitionLogCreate) createSpec() (*RecognitionLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RecognitionLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recognitionlog.Table, sqlgraph.NewFieldSpec(recognitionlog.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CameraID(); ok {
		_spec.SetField(recognitionlog.FieldCameraID, field.TypeString, value)
		_node.CameraID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(recognitionlog.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(recognitionlog.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.MemberID(); ok {
		_spec.SetField(recognitionlog.FieldMemberID, field.TypeString, value)
		_node.MemberID = value
	}
	if value, ok := _c.mutation.TrackID(); ok {
		_spec.SetField(recognitionlog.FieldTrackID, field.TypeInt, value)
		_node.TrackID = value
	}
	if value, ok := _c.mutation.MessageKey(); ok {
		_spec.SetField(recognitionlog.FieldMessageKey, field.TypeString, value)
		_node.MessageKey = value
	}
	if value, ok := _c.mutation.MessageParams(); ok {
		_spec.SetField(recognitionlog.FieldMessageParams, field.TypeJSON, value)
		_node.MessageParams = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recognitionlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RecognitionLogCreateBulk is the builder for creating many RecognitionLog entities in bulk.
type RecognitionLogCreateBulk struct {
	config
	err      error
	builders []*RecognitionLogCreate
}

// Save creates the RecognitionLog entities in the database.
func (_c *RecognitionLogCreateBulk) Save(ctx context.Context) ([]*RecognitionLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecognitionLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecognitionLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecognitionLogCreateBulk) SaveX(ctx context.Context) []*RecognitionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecognitionLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecognitionLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
