// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/recognitionlog"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RecognitionLog is the model entity for the RecognitionLog schema.
type RecognitionLog struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CameraID holds the value of the "camera_id" field.
	CameraID string `json:"camera_id,omitempty"`
	// member_identified, stranger_detected, fire_detected, smoke_detected, weapon_detected, fall_detected, accident_detected, suspicious
	Type string `json:"type,omitempty"`
	// member (emerald), guest (blue), stranger (red), risk (orange), fall (rose), suspicious (amber)
	Category string `json:"category,omitempty"`
	// MemberID holds the value of the "member_id" field.
	MemberID string `json:"member_id,omitempty"`
	// TrackID holds the value of the "track_id" field.
	TrackID int `json:"track_id,omitempty"`
	// MessageKey holds the value of the "message_key" field.
	MessageKey string `json:"message_key,omitempty"`
	// MessageParams holds the value of the "message_params" field.
	MessageParams map[string]string `json:"message_params,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecognitionLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recognitionlog.FieldMessageParams:
			values[i] = new([]byte)
		case recognitionlog.FieldTrackID:
			values[i] = new(sql.NullInt64)
		case recognitionlog.FieldID, recognitionlog.FieldCameraID, recognitionlog.FieldType, recognitionlog.FieldCategory, recognitionlog.FieldMemberID, recognitionlog.FieldMessageKey:
			values[i] = new(sql.NullString)
		case recognitionlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecognitionLog fields.
func (_m *RecognitionLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recognitionlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case recognitionlog.FieldCameraID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field camera_id", values[i])
			} else if value.Valid {
				_m.CameraID = value.String
			}
		case recognitionlog.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case recognitionlog.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case recognitionlog.FieldMemberID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value.Valid {
				_m.MemberID = value.String
			}
		case recognitionlog.FieldTrackID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field track_id", values[i])
			} else if value.Valid {
				_m.TrackID = int(value.Int64)
			}
		case recognitionlog.FieldMessageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_key", values[i])
			} else if value.Valid {
				_m.MessageKey = value.String
			}
		case recognitionlog.FieldMessageParams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field message_params", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MessageParams); err != nil {
					return fmt.Errorf("unmarshal field message_params: %w", err)
				}
			}
		case recognitionlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecognitionLog.
// This includes values selected through modifiers, order, etc.
func (_m *RecognitionLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RecognitionLog.
// Note that you need to call RecognitionLog.Unwrap() before calling this method if this RecognitionLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecognitionLog) Update() *RecognitionLogUpdateOne {
	return NewRecognitionLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecognitionLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecognitionLog) Unwrap() *RecognitionLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecognitionLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecognitionLog) String() string {
	var builder strings.Builder
	builder.WriteString("RecognitionLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("camera_id=")
	builder.WriteString(_m.CameraID)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(_m.MemberID)
	builder.WriteString(", ")
	builder.WriteString("track_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrackID))
	builder.WriteString(", ")
	builder.WriteString("message_key=")
	builder.WriteString(_m.MessageKey)
	builder.WriteString(", ")
	builder.WriteString("message_params=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageParams))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RecognitionLogs is a parsable slice of RecognitionLog.
type RecognitionLogs []*RecognitionLog
