// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/camera"
	"cctv/shared/ent/recording"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Recording is the model entity for the Recording schema.
type Recording struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CameraID holds the value of the "camera_id" field.
	CameraID string `json:"camera_id,omitempty"`
	// StartAt holds the value of the "start_at" field.
	StartAt time.Time `json:"start_at,omitempty"`
	// EndAt holds the value of the "end_at" field.
	EndAt time.Time `json:"end_at,omitempty"`
	// DurationSeconds holds the value of the "duration_seconds" field.
	DurationSeconds int `json:"duration_seconds,omitempty"`
	// FilePath holds the value of the "file_path" field.
	FilePath string `json:"file_path,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecordingQuery when eager-loading is set.
	Edges        RecordingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RecordingEdges holds the relations/edges for other nodes in the graph.
type RecordingEdges struct {
	// Camera holds the value of the camera edge.
	Camera *Camera `json:"camera,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CameraOrErr returns the Camera value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecordingEdges) CameraOrErr() (*Camera, error) {
	if e.Camera != nil {
		return e.Camera, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: camera.Label}
	}
	return nil, &NotLoadedError{edge: "camera"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Recording) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recording.FieldDurationSeconds, recording.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case recording.FieldID, recording.FieldCameraID, recording.FieldFilePath:
			values[i] = new(sql.NullString)
		case recording.FieldStartAt, recording.FieldEndAt, recording.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Recording fields.
func (_m *Recording) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recording.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case recording.FieldCameraID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field camera_id", values[i])
			} else if value.Valid {
				_m.CameraID = value.String
			}
		case recording.FieldStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_at", values[i])
			} else if value.Valid {
				_m.StartAt = value.Time
			}
		case recording.FieldEndAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_at", values[i])
			} else if value.Valid {
				_m.EndAt = value.Time
			}
		case recording.FieldDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_seconds", values[i])
			} else if value.Valid {
				_m.DurationSeconds = int(value.Int64)
			}
		case recording.FieldFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_path", values[i])
			} else if value.Valid {
				_m.FilePath = value.String
			}
		case recording.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case recording.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Recording.
// This includes values selected through modifiers, order, etc.
func (_m *Recording) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCamera queries the "camera" edge of the Recording entity.
func (_m *Recording) QueryCamera() *CameraQuery {
	return NewRecordingClient(_m.config).QueryCamera(_m)
}

// Update returns a builder for updating this Recording.
// Note that you need to call Recording.Unwrap() before calling this method if this Recording
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Recording) Update() *RecordingUpdateOne {
	return NewRecordingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Recording entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Recording) Unwrap() *Recording {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Recording is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Recording) String() string {
	var builder strings.Builder
	builder.WriteString("Recording(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("camera_id=")
	builder.WriteString(_m.CameraID)
	builder.WriteString(", ")
	builder.WriteString("start_at=")
	builder.WriteString(_m.StartAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_at=")
	builder.WriteString(_m.EndAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationSeconds))
	builder.WriteString(", ")
	builder.WriteString("file_path=")
	builder.WriteString(_m.FilePath)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Recordings is a parsable slice of Recording.
type Recordings []*Recording
