// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/predicate"
	"cctv/shared/ent/recognitionlog"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecognitionLogDelete is the builder for deleting a RecognitionLog entity.
type RecognitionLogDelete struct {
	config
	hooks    []Hook
	mutation *RecognitionLogMutation
}

// Where appends a list predicates to the RecognitionLogDelete builder.
func (_d *RecognitionLogDelete) Where(ps ...predicate.RecognitionLog) *RecognitionLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RecognitionLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecognitionLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RecognitionLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recognitionlog.Table, sqlgraph.NewFieldSpec(recognitionlog.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RecognitionLogDeleteOne is the builder for deleting a single RecognitionLog entity.
type RecognitionLogDeleteOne struct {
	_d *RecognitionLogDelete
}

// Where appends a list predicates to the RecognitionLogDelete builder.
func (_d *RecognitionLogDeleteOne) Where(ps ...predicate.RecognitionLog) *RecognitionLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RecognitionLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recognitionlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecognitionLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
