// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/camera"
	"cctv/shared/ent/member"
	"cctv/shared/ent/memberface"
	"cctv/shared/ent/notification"
	"cctv/shared/ent/pushsubscription"
	"cctv/shared/ent/recognitionlog"
	"cctv/shared/ent/recording"
	"cctv/shared/ent/schema"
	"cctv/shared/ent/session"
	"cctv/shared/ent/setting"
	"cctv/shared/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cameraFields := schema.Camera{}.Fields()
	_ = cameraFields
	// cameraDescName is the schema descriptor for name field.
	cameraDescName := cameraFields[1].Descriptor()
	// camera.NameValidator is a validator for the "name" field. It is called by the builders before save.
	camera.NameValidator = cameraDescName.Validators[0].(func(string) error)
	// cameraDescHost is the schema descriptor for host field.
	cameraDescHost := cameraFields[2].Descriptor()
	// camera.HostValidator is a validator for the "host" field. It is called by the builders before save.
	camera.HostValidator = cameraDescHost.Validators[0].(func(string) error)
	// cameraDescBrand is the schema descriptor for brand field.
	cameraDescBrand := cameraFields[3].Descriptor()
	// camera.DefaultBrand holds the default value on creation for the brand field.
	camera.DefaultBrand = cameraDescBrand.Default.(string)
	// cameraDescRtspPort is the schema descriptor for rtsp_port field.
	cameraDescRtspPort := cameraFields[4].Descriptor()
	// camera.DefaultRtspPort holds the default value on creation for the rtsp_port field.
	camera.DefaultRtspPort = cameraDescRtspPort.Default.(int)
	// cameraDescRtspTransport is the schema descriptor for rtsp_transport field.
	cameraDescRtspTransport := cameraFields[5].Descriptor()
	// camera.DefaultRtspTransport holds the default value on creation for the rtsp_transport field.
	camera.DefaultRtspTransport = cameraDescRtspTransport.Default.(string)
	// cameraDescSegmentDuration is the schema descriptor for segment_duration field.
	cameraDescSegmentDuration := cameraFields[6].Descriptor()
	// camera.DefaultSegmentDuration holds the default value on creation for the segment_duration field.
	camera.DefaultSegmentDuration = cameraDescSegmentDuration.Default.(int)
	// cameraDescVideoCodec is the schema descriptor for video_codec field.
	cameraDescVideoCodec := cameraFields[7].Descriptor()
	// camera.DefaultVideoCodec holds the default value on creation for the video_codec field.
	camera.DefaultVideoCodec = cameraDescVideoCodec.Default.(string)
	// cameraDescAudioMode is the schema descriptor for audio_mode field.
	cameraDescAudioMode := cameraFields[8].Descriptor()
	// camera.DefaultAudioMode holds the default value on creation for the audio_mode field.
	camera.DefaultAudioMode = cameraDescAudioMode.Default.(string)
	// cameraDescExtraArgs is the schema descriptor for extra_args field.
	cameraDescExtraArgs := cameraFields[9].Descriptor()
	// camera.DefaultExtraArgs holds the default value on creation for the extra_args field.
	camera.DefaultExtraArgs = cameraDescExtraArgs.Default.(string)
	// cameraDescIsActive is the schema descriptor for is_active field.
	cameraDescIsActive := cameraFields[10].Descriptor()
	// camera.DefaultIsActive holds the default value on creation for the is_active field.
	camera.DefaultIsActive = cameraDescIsActive.Default.(bool)
	// cameraDescIsStopped is the schema descriptor for is_stopped field.
	cameraDescIsStopped := cameraFields[11].Descriptor()
	// camera.DefaultIsStopped holds the default value on creation for the is_stopped field.
	camera.DefaultIsStopped = cameraDescIsStopped.Default.(bool)
	// cameraDescEnableAi is the schema descriptor for enable_ai field.
	cameraDescEnableAi := cameraFields[12].Descriptor()
	// camera.DefaultEnableAi holds the default value on creation for the enable_ai field.
	camera.DefaultEnableAi = cameraDescEnableAi.Default.(bool)
	// cameraDescShowBbox is the schema descriptor for show_bbox field.
	cameraDescShowBbox := cameraFields[13].Descriptor()
	// camera.DefaultShowBbox holds the default value on creation for the show_bbox field.
	camera.DefaultShowBbox = cameraDescShowBbox.Default.(bool)
	// cameraDescCreatedAt is the schema descriptor for created_at field.
	cameraDescCreatedAt := cameraFields[14].Descriptor()
	// camera.DefaultCreatedAt holds the default value on creation for the created_at field.
	camera.DefaultCreatedAt = cameraDescCreatedAt.Default.(func() time.Time)
	// cameraDescUpdatedAt is the schema descriptor for updated_at field.
	cameraDescUpdatedAt := cameraFields[15].Descriptor()
	// camera.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	camera.DefaultUpdatedAt = cameraDescUpdatedAt.Default.(func() time.Time)
	// camera.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	camera.UpdateDefaultUpdatedAt = cameraDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cameraDescID is the schema descriptor for id field.
	cameraDescID := cameraFields[0].Descriptor()
	// camera.DefaultID holds the default value on creation for the id field.
	camera.DefaultID = cameraDescID.Default.(func() string)
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescName is the schema descriptor for name field.
	memberDescName := memberFields[1].Descriptor()
	// member.NameValidator is a validator for the "name" field. It is called by the builders before save.
	member.NameValidator = memberDescName.Validators[0].(func(string) error)
	// memberDescAvatarURL is the schema descriptor for avatar_url field.
	memberDescAvatarURL := memberFields[3].Descriptor()
	// member.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	member.DefaultAvatarURL = memberDescAvatarURL.Default.(string)
	// memberDescIsActive is the schema descriptor for is_active field.
	memberDescIsActive := memberFields[4].Descriptor()
	// member.DefaultIsActive holds the default value on creation for the is_active field.
	member.DefaultIsActive = memberDescIsActive.Default.(bool)
	// memberDescCreatedAt is the schema descriptor for created_at field.
	memberDescCreatedAt := memberFields[5].Descriptor()
	// member.DefaultCreatedAt holds the default value on creation for the created_at field.
	member.DefaultCreatedAt = memberDescCreatedAt.Default.(func() time.Time)
	// memberDescUpdatedAt is the schema descriptor for updated_at field.
	memberDescUpdatedAt := memberFields[6].Descriptor()
	// member.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	member.DefaultUpdatedAt = memberDescUpdatedAt.Default.(func() time.Time)
	// member.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	member.UpdateDefaultUpdatedAt = memberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memberDescID is the schema descriptor for id field.
	memberDescID := memberFields[0].Descriptor()
	// member.DefaultID holds the default value on creation for the id field.
	member.DefaultID = memberDescID.Default.(func() string)
	memberfaceFields := schema.MemberFace{}.Fields()
	_ = memberfaceFields
	// memberfaceDescSampleImageURL is the schema descriptor for sample_image_url field.
	memberfaceDescSampleImageURL := memberfaceFields[3].Descriptor()
	// memberface.DefaultSampleImageURL holds the default value on creation for the sample_image_url field.
	memberface.DefaultSampleImageURL = memberfaceDescSampleImageURL.Default.(string)
	// memberfaceDescQualityScore is the schema descriptor for quality_score field.
	memberfaceDescQualityScore := memberfaceFields[4].Descriptor()
	// memberface.DefaultQualityScore holds the default value on creation for the quality_score field.
	memberface.DefaultQualityScore = memberfaceDescQualityScore.Default.(float64)
	// memberfaceDescYaw is the schema descriptor for yaw field.
	memberfaceDescYaw := memberfaceFields[5].Descriptor()
	// memberface.DefaultYaw holds the default value on creation for the yaw field.
	memberface.DefaultYaw = memberfaceDescYaw.Default.(float64)
	// memberfaceDescPitch is the schema descriptor for pitch field.
	memberfaceDescPitch := memberfaceFields[6].Descriptor()
	// memberface.DefaultPitch holds the default value on creation for the pitch field.
	memberface.DefaultPitch = memberfaceDescPitch.Default.(float64)
	// memberfaceDescBlurScore is the schema descriptor for blur_score field.
	memberfaceDescBlurScore := memberfaceFields[7].Descriptor()
	// memberface.DefaultBlurScore holds the default value on creation for the blur_score field.
	memberface.DefaultBlurScore = memberfaceDescBlurScore.Default.(float64)
	// memberfaceDescIsActive is the schema descriptor for is_active field.
	memberfaceDescIsActive := memberfaceFields[8].Descriptor()
	// memberface.DefaultIsActive holds the default value on creation for the is_active field.
	memberface.DefaultIsActive = memberfaceDescIsActive.Default.(bool)
	// memberfaceDescCreatedAt is the schema descriptor for created_at field.
	memberfaceDescCreatedAt := memberfaceFields[9].Descriptor()
	// memberface.DefaultCreatedAt holds the default value on creation for the created_at field.
	memberface.DefaultCreatedAt = memberfaceDescCreatedAt.Default.(func() time.Time)
	// memberfaceDescID is the schema descriptor for id field.
	memberfaceDescID := memberfaceFields[0].Descriptor()
	// memberface.DefaultID holds the default value on creation for the id field.
	memberface.DefaultID = memberfaceDescID.Default.(func() string)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescCameraID is the schema descriptor for camera_id field.
	notificationDescCameraID := notificationFields[1].Descriptor()
	// notification.DefaultCameraID holds the default value on creation for the camera_id field.
	notification.DefaultCameraID = notificationDescCameraID.Default.(string)
	// notificationDescType is the schema descriptor for type field.
	notificationDescType := notificationFields[2].Descriptor()
	// notification.DefaultType holds the default value on creation for the type field.
	notification.DefaultType = notificationDescType.Default.(string)
	// notificationDescTitle is the schema descriptor for title field.
	notificationDescTitle := notificationFields[3].Descriptor()
	// notification.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	notification.TitleValidator = notificationDescTitle.Validators[0].(func(string) error)
	// notificationDescBody is the schema descriptor for body field.
	notificationDescBody := notificationFields[4].Descriptor()
	// notification.DefaultBody holds the default value on creation for the body field.
	notification.DefaultBody = notificationDescBody.Default.(string)
	// notificationDescCategory is the schema descriptor for category field.
	notificationDescCategory := notificationFields[5].Descriptor()
	// notification.DefaultCategory holds the default value on creation for the category field.
	notification.DefaultCategory = notificationDescCategory.Default.(string)
	// notificationDescMemberID is the schema descriptor for member_id field.
	notificationDescMemberID := notificationFields[6].Descriptor()
	// notification.DefaultMemberID holds the default value on creation for the member_id field.
	notification.DefaultMemberID = notificationDescMemberID.Default.(string)
	// notificationDescThumbnailURL is the schema descriptor for thumbnail_url field.
	notificationDescThumbnailURL := notificationFields[7].Descriptor()
	// notification.DefaultThumbnailURL holds the default value on creation for the thumbnail_url field.
	notification.DefaultThumbnailURL = notificationDescThumbnailURL.Default.(string)
	// notificationDescIsRead is the schema descriptor for is_read field.
	notificationDescIsRead := notificationFields[8].Descriptor()
	// notification.DefaultIsRead holds the default value on creation for the is_read field.
	notification.DefaultIsRead = notificationDescIsRead.Default.(bool)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[9].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() string)
	pushsubscriptionFields := schema.PushSubscription{}.Fields()
	_ = pushsubscriptionFields
	// pushsubscriptionDescUserID is the schema descriptor for user_id field.
	pushsubscriptionDescUserID := pushsubscriptionFields[1].Descriptor()
	// pushsubscription.DefaultUserID holds the default value on creation for the user_id field.
	pushsubscription.DefaultUserID = pushsubscriptionDescUserID.Default.(string)
	// pushsubscriptionDescEndpoint is the schema descriptor for endpoint field.
	pushsubscriptionDescEndpoint := pushsubscriptionFields[2].Descriptor()
	// pushsubscription.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	pushsubscription.EndpointValidator = pushsubscriptionDescEndpoint.Validators[0].(func(string) error)
	// pushsubscriptionDescP256dh is the schema descriptor for p256dh field.
	pushsubscriptionDescP256dh := pushsubscriptionFields[3].Descriptor()
	// pushsubscription.P256dhValidator is a validator for the "p256dh" field. It is called by the builders before save.
	pushsubscription.P256dhValidator = pushsubscriptionDescP256dh.Validators[0].(func(string) error)
	// pushsubscriptionDescAuth is the schema descriptor for auth field.
	pushsubscriptionDescAuth := pushsubscriptionFields[4].Descriptor()
	// pushsubscription.AuthValidator is a validator for the "auth" field. It is called by the builders before save.
	pushsubscription.AuthValidator = pushsubscriptionDescAuth.Validators[0].(func(string) error)
	// pushsubscriptionDescUserAgent is the schema descriptor for user_agent field.
	pushsubscriptionDescUserAgent := pushsubscriptionFields[5].Descriptor()
	// pushsubscription.DefaultUserAgent holds the default value on creation for the user_agent field.
	pushsubscription.DefaultUserAgent = pushsubscriptionDescUserAgent.Default.(string)
	// pushsubscriptionDescCreatedAt is the schema descriptor for created_at field.
	pushsubscriptionDescCreatedAt := pushsubscriptionFields[6].Descriptor()
	// pushsubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	pushsubscription.DefaultCreatedAt = pushsubscriptionDescCreatedAt.Default.(func() time.Time)
	// pushsubscriptionDescID is the schema descriptor for id field.
	pushsubscriptionDescID := pushsubscriptionFields[0].Descriptor()
	// pushsubscription.DefaultID holds the default value on creation for the id field.
	pushsubscription.DefaultID = pushsubscriptionDescID.Default.(func() string)
	recognitionlogFields := schema.RecognitionLog{}.Fields()
	_ = recognitionlogFields
	// recognitionlogDescCameraID is the schema descriptor for camera_id field.
	recognitionlogDescCameraID := recognitionlogFields[1].Descriptor()
	// recognitionlog.CameraIDValidator is a validator for the "camera_id" field. It is called by the builders before save.
	recognitionlog.CameraIDValidator = recognitionlogDescCameraID.Validators[0].(func(string) error)
	// recognitionlogDescType is the schema descriptor for type field.
	recognitionlogDescType := recognitionlogFields[2].Descriptor()
	// recognitionlog.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	recognitionlog.TypeValidator = recognitionlogDescType.Validators[0].(func(string) error)
	// recognitionlogDescCategory is the schema descriptor for category field.
	recognitionlogDescCategory := recognitionlogFields[3].Descriptor()
	// recognitionlog.DefaultCategory holds the default value on creation for the category field.
	recognitionlog.DefaultCategory = recognitionlogDescCategory.Default.(string)
	// recognitionlogDescMemberID is the schema descriptor for member_id field.
	recognitionlogDescMemberID := recognitionlogFields[4].Descriptor()
	// recognitionlog.DefaultMemberID holds the default value on creation for the member_id field.
	recognitionlog.DefaultMemberID = recognitionlogDescMemberID.Default.(string)
	// recognitionlogDescTrackID is the schema descriptor for track_id field.
	recognitionlogDescTrackID := recognitionlogFields[5].Descriptor()
	// recognitionlog.DefaultTrackID holds the default value on creation for the track_id field.
	recognitionlog.DefaultTrackID = recognitionlogDescTrackID.Default.(int)
	// recognitionlogDescMessageKey is the schema descriptor for message_key field.
	recognitionlogDescMessageKey := recognitionlogFields[6].Descriptor()
	// recognitionlog.MessageKeyValidator is a validator for the "message_key" field. It is called by the builders before save.
	recognitionlog.MessageKeyValidator = recognitionlogDescMessageKey.Validators[0].(func(string) error)
	// recognitionlogDescCreatedAt is the schema descriptor for created_at field.
	recognitionlogDescCreatedAt := recognitionlogFields[8].Descriptor()
	// recognitionlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	recognitionlog.DefaultCreatedAt = recognitionlogDescCreatedAt.Default.(func() time.Time)
	// recognitionlogDescID is the schema descriptor for id field.
	recognitionlogDescID := recognitionlogFields[0].Descriptor()
	// recognitionlog.DefaultID holds the default value on creation for the id field.
	recognitionlog.DefaultID = recognitionlogDescID.Default.(func() string)
	recordingFields := schema.Recording{}.Fields()
	_ = recordingFields
	// recordingDescCreatedAt is the schema descriptor for created_at field.
	recordingDescCreatedAt := recordingFields[8].Descriptor()
	// recording.DefaultCreatedAt holds the default value on creation for the created_at field.
	recording.DefaultCreatedAt = recordingDescCreatedAt.Default.(func() time.Time)
	// recordingDescID is the schema descriptor for id field.
	recordingDescID := recordingFields[0].Descriptor()
	// recording.DefaultID holds the default value on creation for the id field.
	recording.DefaultID = recordingDescID.Default.(func() string)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescIsPwa is the schema descriptor for is_pwa field.
	sessionDescIsPwa := sessionFields[4].Descriptor()
	// session.DefaultIsPwa holds the default value on creation for the is_pwa field.
	session.DefaultIsPwa = sessionDescIsPwa.Default.(bool)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[6].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() string)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescNvrStatus is the schema descriptor for nvr_status field.
	settingDescNvrStatus := settingFields[1].Descriptor()
	// setting.DefaultNvrStatus holds the default value on creation for the nvr_status field.
	setting.DefaultNvrStatus = settingDescNvrStatus.Default.(bool)
	// settingDescStorageQuotaGB is the schema descriptor for storage_quota_gb field.
	settingDescStorageQuotaGB := settingFields[2].Descriptor()
	// setting.DefaultStorageQuotaGB holds the default value on creation for the storage_quota_gb field.
	setting.DefaultStorageQuotaGB = settingDescStorageQuotaGB.Default.(int)
	// settingDescRetentionDays is the schema descriptor for retention_days field.
	settingDescRetentionDays := settingFields[3].Descriptor()
	// setting.DefaultRetentionDays holds the default value on creation for the retention_days field.
	setting.DefaultRetentionDays = settingDescRetentionDays.Default.(int)
	// settingDescID is the schema descriptor for id field.
	settingDescID := settingFields[0].Descriptor()
	// setting.DefaultID holds the default value on creation for the id field.
	setting.DefaultID = settingDescID.Default.(func() string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescFullName is the schema descriptor for full_name field.
	userDescFullName := userFields[2].Descriptor()
	// user.DefaultFullName holds the default value on creation for the full_name field.
	user.DefaultFullName = userDescFullName.Default.(string)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[5].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescTimezone is the schema descriptor for timezone field.
	userDescTimezone := userFields[7].Descriptor()
	// user.DefaultTimezone holds the default value on creation for the timezone field.
	user.DefaultTimezone = userDescTimezone.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[8].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[9].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPushPreferences is the schema descriptor for push_preferences field.
	userDescPushPreferences := userFields[11].Descriptor()
	// user.DefaultPushPreferences holds the default value on creation for the push_preferences field.
	user.DefaultPushPreferences = userDescPushPreferences.Default.(map[string]bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
