// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cctv/shared/ent/setting"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SettingCreate is the builder for creating a Setting entity.
type SettingCreate struct {
	config
	mutation *SettingMutation
	hooks    []Hook
}

// SetNvrStatus sets the "nvr_status" field.
func (_c *SettingCreate) SetNvrStatus(v bool) *SettingCreate {
	_c.mutation.SetNvrStatus(v)
	return _c
}

// SetNillableNvrStatus sets the "nvr_status" field if the given value is not nil.
func (_c *SettingCreate) SetNillableNvrStatus(v *bool) *SettingCreate {
	if v != nil {
		_c.SetNvrStatus(*v)
	}
	return _c
}

// SetStorageQuotaGB sets the "storage_quota_gb" field.
func (_c *SettingCreate) SetStorageQuotaGB(v int) *SettingCreate {
	_c.mutation.SetStorageQuotaGB(v)
	return _c
}

// SetNillableStorageQuotaGB sets the "storage_quota_gb" field if the given value is not nil.
func (_c *SettingCreate) SetNillableStorageQuotaGB(v *int) *SettingCreate {
	if v != nil {
		_c.SetStorageQuotaGB(*v)
	}
	return _c
}

// SetRetentionDays sets the "retention_days" field.
func (_c *SettingCreate) SetRetentionDays(v int) *SettingCreate {
	_c.mutation.SetRetentionDays(v)
	return _c
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_c *SettingCreate) SetNillableRetentionDays(v *int) *SettingCreate {
	if v != nil {
		_c.SetRetentionDays(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SettingCreate) SetID(v string) *SettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SettingCreate) SetNillableID(v *string) *SettingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SettingMutation object of the builder.
func (_c *SettingCreate) Mutation() *SettingMutation {
	return _c.mutation
}

// Save creates the Setting in the database.
func (_c *SettingCreate) Save(ctx context.Context) (*Setting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SettingCreate) SaveX(ctx context.Context) *Setting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SettingCreate) defaults() {
	if _, ok := _c.mutation.NvrStatus(); !ok {
		v := setting.DefaultNvrStatus
		_c.mutation.SetNvrStatus(v)
	}
	if _, ok := _c.mutation.StorageQuotaGB(); !ok {
		v := setting.DefaultStorageQuotaGB
		_c.mutation.SetStorageQuotaGB(v)
	}
	if _, ok := _c.mutation.RetentionDays(); !ok {
		v := setting.DefaultRetentionDays
		_c.mutation.SetRetentionDays(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := setting.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SettingCreate) check() error {
	if _, ok := _c.mutation.NvrStatus(); !ok {
		return &ValidationError{Name: "nvr_status", err: errors.New(`ent: missing required field "Setting.nvr_status"`)}
	}
	if _, ok := _c.mutation.StorageQuotaGB(); !ok {
		return &ValidationError{Name: "storage_quota_gb", err: errors.New(`ent: missing required field "Setting.storage_quota_gb"`)}
	}
	if _, ok := _c.mutation.RetentionDays(); !ok {
		return &ValidationError{Name: "retention_days", err: errors.New(`ent: missing required field "Setting.retention_days"`)}
	}
	return nil
}

func (_c *SettingCreate) sqlSave(ctx context.Context) (*Setting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Setting.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SettingCreate) createSpec() (*Setting, *sqlgraph.CreateSpec) {
	var (
		_node = &Setting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(setting.Table, sqlgraph.NewFieldSpec(setting.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.NvrStatus(); ok {
		_spec.SetField(setting.FieldNvrStatus, field.TypeBool, value)
		_node.NvrStatus = value
	}
	if value, ok := _c.mutation.StorageQuotaGB(); ok {
		_spec.SetField(setting.FieldStorageQuotaGB, field.TypeInt, value)
		_node.StorageQuotaGB = value
	}
	if value, ok := _c.mutation.RetentionDays(); ok {
		_spec.SetField(setting.FieldRetentionDays, field.TypeInt, value)
		_node.RetentionDays = value
	}
	return _node, _spec
}

// SettingCreateBulk is the builder for creating many Setting entities in bulk.
type SettingCreateBulk struct {
	config
	err      error
	builders []*SettingCreate
}

// Save creates the Setting entities in the database.
func (_c *SettingCreateBulk) Save(ctx context.Context) ([]*Setting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Setting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SettingCreateBulk) SaveX(ctx context.Context) []*Setting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
