// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CamerasColumns holds the columns for the "cameras" table.
	CamerasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "host", Type: field.TypeString},
		{Name: "brand", Type: field.TypeString, Default: "generic"},
		{Name: "rtsp_port", Type: field.TypeInt, Default: 554},
		{Name: "rtsp_transport", Type: field.TypeString, Default: "auto"},
		{Name: "segment_duration", Type: field.TypeInt, Default: 1800},
		{Name: "video_codec", Type: field.TypeString, Default: "copy"},
		{Name: "audio_mode", Type: field.TypeString, Default: "auto"},
		{Name: "extra_args", Type: field.TypeString, Default: ""},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "enable_ai", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CamerasTable holds the schema information for the "cameras" table.
	CamerasTable = &schema.Table{
		Name:       "cameras",
		Columns:    CamerasColumns,
		PrimaryKey: []*schema.Column{CamerasColumns[0]},
	}
	// MembersColumns holds the columns for the "members" table.
	MembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"family", "guest", "neighbor", "staff"}, Default: "family"},
		{Name: "avatar_url", Type: field.TypeString, Default: ""},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MembersTable holds the schema information for the "members" table.
	MembersTable = &schema.Table{
		Name:       "members",
		Columns:    MembersColumns,
		PrimaryKey: []*schema.Column{MembersColumns[0]},
	}
	// MemberFacesColumns holds the columns for the "member_faces" table.
	MemberFacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "embedding", Type: field.TypeJSON},
		{Name: "sample_image_url", Type: field.TypeString, Default: ""},
		{Name: "quality_score", Type: field.TypeFloat64, Default: 0},
		{Name: "yaw", Type: field.TypeFloat64, Default: 0},
		{Name: "pitch", Type: field.TypeFloat64, Default: 0},
		{Name: "blur_score", Type: field.TypeFloat64, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "member_id", Type: field.TypeString},
	}
	// MemberFacesTable holds the schema information for the "member_faces" table.
	MemberFacesTable = &schema.Table{
		Name:       "member_faces",
		Columns:    MemberFacesColumns,
		PrimaryKey: []*schema.Column{MemberFacesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_faces_members_faces",
				Columns:    []*schema.Column{MemberFacesColumns[9]},
				RefColumns: []*schema.Column{MembersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "camera_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "type", Type: field.TypeString, Default: "person_identified"},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Default: ""},
		{Name: "category", Type: field.TypeString, Default: "family"},
		{Name: "member_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "thumbnail_url", Type: field.TypeString, Default: ""},
		{Name: "is_read", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
	}
	// PushSubscriptionsColumns holds the columns for the "push_subscriptions" table.
	PushSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "endpoint", Type: field.TypeString, Unique: true},
		{Name: "p256dh", Type: field.TypeString},
		{Name: "auth", Type: field.TypeString},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PushSubscriptionsTable holds the schema information for the "push_subscriptions" table.
	PushSubscriptionsTable = &schema.Table{
		Name:       "push_subscriptions",
		Columns:    PushSubscriptionsColumns,
		PrimaryKey: []*schema.Column{PushSubscriptionsColumns[0]},
	}
	// RecordingsColumns holds the columns for the "recordings" table.
	RecordingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "start_at", Type: field.TypeTime},
		{Name: "end_at", Type: field.TypeTime},
		{Name: "duration_seconds", Type: field.TypeInt},
		{Name: "file_path", Type: field.TypeString, Unique: true},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "camera_id", Type: field.TypeString},
	}
	// RecordingsTable holds the schema information for the "recordings" table.
	RecordingsTable = &schema.Table{
		Name:       "recordings",
		Columns:    RecordingsColumns,
		PrimaryKey: []*schema.Column{RecordingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recordings_cameras_recordings",
				Columns:    []*schema.Column{RecordingsColumns[7]},
				RefColumns: []*schema.Column{CamerasColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeBytes, Unique: true},
		{Name: "refresh_token_hash", Type: field.TypeBytes, Nullable: true},
		{Name: "is_pwa", Type: field.TypeBool, Default: false},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "nvr_status", Type: field.TypeBool, Default: true},
		{Name: "storage_quota_gb", Type: field.TypeInt, Default: 50},
		{Name: "retention_days", Type: field.TypeInt, Default: 4},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "full_name", Type: field.TypeString, Default: ""},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "viewer"}, Default: "viewer"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "locale", Type: field.TypeEnum, Enums: []string{"vi", "en"}, Default: "vi"},
		{Name: "timezone", Type: field.TypeString, Default: "Asia/Ho_Chi_Minh"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CamerasTable,
		MembersTable,
		MemberFacesTable,
		NotificationsTable,
		PushSubscriptionsTable,
		RecordingsTable,
		SessionsTable,
		SettingsTable,
		UsersTable,
	}
)

func init() {
	MemberFacesTable.ForeignKeys[0].RefTable = MembersTable
	RecordingsTable.ForeignKeys[0].RefTable = CamerasTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
}
