// Code generated by ent, DO NOT EDIT.

package recording

import (
	"cctv/shared/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Recording {
	return predicate.Recording(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Recording {
	return predicate.Recording(sql.FieldContainsFold(FieldID, id))
}

// CameraID applies equality check predicate on the "camera_id" field. It's identical to CameraIDEQ.
func CameraID(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldCameraID, v))
}

// StartAt applies equality check predicate on the "start_at" field. It's identical to StartAtEQ.
func StartAt(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldStartAt, v))
}

// EndAt applies equality check predicate on the "end_at" field. It's identical to EndAtEQ.
func EndAt(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldEndAt, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v int) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldDurationSeconds, v))
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldFilePath, v))
}

// ThumbnailPath applies equality check predicate on the "thumbnail_path" field. It's identical to ThumbnailPathEQ.
func ThumbnailPath(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldThumbnailPath, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldSizeBytes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldCreatedAt, v))
}

// CameraIDEQ applies the EQ predicate on the "camera_id" field.
func CameraIDEQ(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldCameraID, v))
}

// CameraIDNEQ applies the NEQ predicate on the "camera_id" field.
func CameraIDNEQ(v string) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldCameraID, v))
}

// CameraIDIn applies the In predicate on the "camera_id" field.
func CameraIDIn(vs ...string) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldCameraID, vs...))
}

// CameraIDNotIn applies the NotIn predicate on the "camera_id" field.
func CameraIDNotIn(vs ...string) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldCameraID, vs...))
}

// CameraIDGT applies the GT predicate on the "camera_id" field.
func CameraIDGT(v string) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldCameraID, v))
}

// CameraIDGTE applies the GTE predicate on the "camera_id" field.
func CameraIDGTE(v string) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldCameraID, v))
}

// CameraIDLT applies the LT predicate on the "camera_id" field.
func CameraIDLT(v string) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldCameraID, v))
}

// CameraIDLTE applies the LTE predicate on the "camera_id" field.
func CameraIDLTE(v string) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldCameraID, v))
}

// CameraIDContains applies the Contains predicate on the "camera_id" field.
func CameraIDContains(v string) predicate.Recording {
	return predicate.Recording(sql.FieldContains(FieldCameraID, v))
}

// CameraIDHasPrefix applies the HasPrefix predicate on the "camera_id" field.
func CameraIDHasPrefix(v string) predicate.Recording {
	return predicate.Recording(sql.FieldHasPrefix(FieldCameraID, v))
}

// CameraIDHasSuffix applies the HasSuffix predicate on the "camera_id" field.
func CameraIDHasSuffix(v string) predicate.Recording {
	return predicate.Recording(sql.FieldHasSuffix(FieldCameraID, v))
}

// CameraIDEqualFold applies the EqualFold predicate on the "camera_id" field.
func CameraIDEqualFold(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEqualFold(FieldCameraID, v))
}

// CameraIDContainsFold applies the ContainsFold predicate on the "camera_id" field.
func CameraIDContainsFold(v string) predicate.Recording {
	return predicate.Recording(sql.FieldContainsFold(FieldCameraID, v))
}

// StartAtEQ applies the EQ predicate on the "start_at" field.
func StartAtEQ(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldStartAt, v))
}

// StartAtNEQ applies the NEQ predicate on the "start_at" field.
func StartAtNEQ(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldStartAt, v))
}

// StartAtIn applies the In predicate on the "start_at" field.
func StartAtIn(vs ...time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldStartAt, vs...))
}

// StartAtNotIn applies the NotIn predicate on the "start_at" field.
func StartAtNotIn(vs ...time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldStartAt, vs...))
}

// StartAtGT applies the GT predicate on the "start_at" field.
func StartAtGT(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldStartAt, v))
}

// StartAtGTE applies the GTE predicate on the "start_at" field.
func StartAtGTE(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldStartAt, v))
}

// StartAtLT applies the LT predicate on the "start_at" field.
func StartAtLT(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldStartAt, v))
}

// StartAtLTE applies the LTE predicate on the "start_at" field.
func StartAtLTE(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldStartAt, v))
}

// EndAtEQ applies the EQ predicate on the "end_at" field.
func EndAtEQ(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldEndAt, v))
}

// EndAtNEQ applies the NEQ predicate on the "end_at" field.
func EndAtNEQ(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldEndAt, v))
}

// EndAtIn applies the In predicate on the "end_at" field.
func EndAtIn(vs ...time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldEndAt, vs...))
}

// EndAtNotIn applies the NotIn predicate on the "end_at" field.
func EndAtNotIn(vs ...time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldEndAt, vs...))
}

// EndAtGT applies the GT predicate on the "end_at" field.
func EndAtGT(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldEndAt, v))
}

// EndAtGTE applies the GTE predicate on the "end_at" field.
func EndAtGTE(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldEndAt, v))
}

// EndAtLT applies the LT predicate on the "end_at" field.
func EndAtLT(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldEndAt, v))
}

// EndAtLTE applies the LTE predicate on the "end_at" field.
func EndAtLTE(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldEndAt, v))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v int) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v int) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...int) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...int) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v int) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v int) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v int) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v int) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldDurationSeconds, v))
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.Recording {
	return predicate.Recording(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.Recording {
	return predicate.Recording(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.Recording {
	return predicate.Recording(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.Recording {
	return predicate.Recording(sql.FieldContainsFold(FieldFilePath, v))
}

// ThumbnailPathEQ applies the EQ predicate on the "thumbnail_path" field.
func ThumbnailPathEQ(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldThumbnailPath, v))
}

// ThumbnailPathNEQ applies the NEQ predicate on the "thumbnail_path" field.
func ThumbnailPathNEQ(v string) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldThumbnailPath, v))
}

// ThumbnailPathIn applies the In predicate on the "thumbnail_path" field.
func ThumbnailPathIn(vs ...string) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldThumbnailPath, vs...))
}

// ThumbnailPathNotIn applies the NotIn predicate on the "thumbnail_path" field.
func ThumbnailPathNotIn(vs ...string) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldThumbnailPath, vs...))
}

// ThumbnailPathGT applies the GT predicate on the "thumbnail_path" field.
func ThumbnailPathGT(v string) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldThumbnailPath, v))
}

// ThumbnailPathGTE applies the GTE predicate on the "thumbnail_path" field.
func ThumbnailPathGTE(v string) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldThumbnailPath, v))
}

// ThumbnailPathLT applies the LT predicate on the "thumbnail_path" field.
func ThumbnailPathLT(v string) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldThumbnailPath, v))
}

// ThumbnailPathLTE applies the LTE predicate on the "thumbnail_path" field.
func ThumbnailPathLTE(v string) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldThumbnailPath, v))
}

// ThumbnailPathContains applies the Contains predicate on the "thumbnail_path" field.
func ThumbnailPathContains(v string) predicate.Recording {
	return predicate.Recording(sql.FieldContains(FieldThumbnailPath, v))
}

// ThumbnailPathHasPrefix applies the HasPrefix predicate on the "thumbnail_path" field.
func ThumbnailPathHasPrefix(v string) predicate.Recording {
	return predicate.Recording(sql.FieldHasPrefix(FieldThumbnailPath, v))
}

// ThumbnailPathHasSuffix applies the HasSuffix predicate on the "thumbnail_path" field.
func ThumbnailPathHasSuffix(v string) predicate.Recording {
	return predicate.Recording(sql.FieldHasSuffix(FieldThumbnailPath, v))
}

// ThumbnailPathIsNil applies the IsNil predicate on the "thumbnail_path" field.
func ThumbnailPathIsNil() predicate.Recording {
	return predicate.Recording(sql.FieldIsNull(FieldThumbnailPath))
}

// ThumbnailPathNotNil applies the NotNil predicate on the "thumbnail_path" field.
func ThumbnailPathNotNil() predicate.Recording {
	return predicate.Recording(sql.FieldNotNull(FieldThumbnailPath))
}

// ThumbnailPathEqualFold applies the EqualFold predicate on the "thumbnail_path" field.
func ThumbnailPathEqualFold(v string) predicate.Recording {
	return predicate.Recording(sql.FieldEqualFold(FieldThumbnailPath, v))
}

// ThumbnailPathContainsFold applies the ContainsFold predicate on the "thumbnail_path" field.
func ThumbnailPathContainsFold(v string) predicate.Recording {
	return predicate.Recording(sql.FieldContainsFold(FieldThumbnailPath, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldSizeBytes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Recording {
	return predicate.Recording(sql.FieldLTE(FieldCreatedAt, v))
}

// HasCamera applies the HasEdge predicate on the "camera" edge.
func HasCamera() predicate.Recording {
	return predicate.Recording(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CameraTable, CameraColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCameraWith applies the HasEdge predicate on the "camera" edge with a given conditions (other predicates).
func HasCameraWith(preds ...predicate.Camera) predicate.Recording {
	return predicate.Recording(func(s *sql.Selector) {
		step := newCameraStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Recording) predicate.Recording {
	return predicate.Recording(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Recording) predicate.Recording {
	return predicate.Recording(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Recording) predicate.Recording {
	return predicate.Recording(sql.NotPredicates(p))
}
