package live

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"cctv/ent"
)

// Hub manages concurrent live streaming sessions across all cameras
type Hub struct {
	mu       sync.RWMutex
	sessions map[int]*Session
	baseDir  string
}

// GlobalHub is the singleton instance of the live streaming hub
var GlobalHub *Hub

func init() {
	tempBase := filepath.Join(os.TempDir(), "cctv_live")
	_ = os.MkdirAll(tempBase, 0755)

	GlobalHub = &Hub{
		sessions: make(map[int]*Session),
		baseDir:  tempBase,
	}

	go GlobalHub.startReaper()
}

// EnsureSession returns an existing live session or spawns a new FFmpeg HLS transcode worker
func (h *Hub) EnsureSession(ctx context.Context, cam *ent.Camera) (*Session, error) {
	h.mu.Lock()
	defer h.mu.Unlock()

	session, exists := h.sessions[cam.ID]
	if exists {
		session.LastAccessed = time.Now()
		return session, nil
	}

	camHlsDir := filepath.Join(h.baseDir, fmt.Sprintf("cam_%d", cam.ID))
	_ = os.RemoveAll(camHlsDir) // Clean stale files
	if err := os.MkdirAll(camHlsDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create HLS directory: %w", err)
	}

	playlistPath := filepath.Join(camHlsDir, "index.m3u8")
	sessionCtx, cancel := context.WithCancel(context.Background())

	session = &Session{
		CameraID:     cam.ID,
		Host:         cam.Host,
		RTSPTransport: cam.RtspTransport,
		AudioMode:    cam.AudioMode,
		ExtraArgs:    cam.ExtraArgs,
		HlsDir:       camHlsDir,
		PlaylistPath: playlistPath,
		LastAccessed: time.Now(),
		Cancel:       cancel,
		Done:         make(chan struct{}),
		IsReady:      false,
	}

	h.sessions[cam.ID] = session

	// Spawn FFmpeg worker goroutine
	go h.runWorker(sessionCtx, session)

	return session, nil
}

// TouchSession updates the last access time for an active live stream
func (h *Hub) TouchSession(cameraID int) {
	h.mu.RLock()
	defer h.mu.RUnlock()

	if s, ok := h.sessions[cameraID]; ok {
		s.LastAccessed = time.Now()
	}
}

// WaitForReady waits up to timeout for the index.m3u8 playlist to be generated by FFmpeg
func (s *Session) WaitForReady(timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(s.PlaylistPath); err == nil {
			s.IsReady = true
			return nil
		}
		time.Sleep(100 * time.Millisecond)
	}
	return fmt.Errorf("timed out waiting for live stream playlist to initialize")
}

func (h *Hub) runWorker(ctx context.Context, s *Session) {
	defer close(s.Done)
	defer func() {
		_ = os.RemoveAll(s.HlsDir)
	}()

	segmentPattern := filepath.Join(s.HlsDir, "seg_%03d.ts")

	transport := s.RTSPTransport
	if transport == "" {
		transport = "tcp"
	}

	args := []string{}
	if transport != "auto" {
		args = append(args, "-rtsp_transport", transport)
	}
	args = append(args, "-stimeout", "5000000")
	args = append(args, "-i", s.Host)

	// Stream copy video for 0% CPU latency
	args = append(args, "-c:v", "copy")

	// Audio handling for HLS
	if s.AudioMode == "disabled" || s.AudioMode == "none" {
		args = append(args, "-an")
	} else {
		// Use AAC for universal browser playback compatibility
		args = append(args, "-c:a", "aac", "-b:a", "128k")
	}

	// Low-latency HLS output configuration
	args = append(args,
		"-f", "hls",
		"-hls_time", "1",
		"-hls_list_size", "4",
		"-hls_flags", "delete_segments+split_by_time",
		"-hls_segment_filename", segmentPattern,
		s.PlaylistPath,
	)

	log.Printf("[Live Hub] Spawning live FFmpeg for camera %d: ffmpeg %s", s.CameraID, strings.Join(args, " "))

	cmd := exec.CommandContext(ctx, "ffmpeg", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil && ctx.Err() == nil {
		log.Printf("[Live Hub] Live FFmpeg worker for camera %d exited: %v", s.CameraID, err)
	}
}

// startReaper periodically reaps idle live streaming sessions
func (h *Hub) startReaper() {
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		h.mu.Lock()
		now := time.Now()
		for id, session := range h.sessions {
			// If no viewer has polled the stream in the last 30 seconds, shut down FFmpeg
			if now.Sub(session.LastAccessed) > 30*time.Second {
				log.Printf("[Live Hub] Camera %d idle timeout reached (30s). Shutting down live stream.", id)
				session.Cancel()
				delete(h.sessions, id)
			}
		}
		h.mu.Unlock()
	}
}
